server.port: 5000

app:
  domains:
    - http://localhost:5000
  forceHttps: false
  oauth2:
    base-url: http://localhost:5100
    realm: test

security:
  oidc:
    required-authority: user-ws
    clientId: ws-pluto
    clientSecret: 00000000-0000-0000-0000-000000000000
    refresh-token-jwk-algorithm: HS256

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: false

keycloak:
  workspace-login-group: ws-users

zuul:
  routes:
    # Please note that the order of the routes is relevant
    # The elasticsearch route must be defined before
    # saturn, which must be defined before ui, because of the
    # paths they listen to
    storage:
      url: http://localhost:8080
    elasticsearch:
      url: http://localhost:9200
    saturn:
      url: http://localhost:8080
    ui:
      url: http://localhost:3000

  include-debug-header: true
