app:
  forceHttps: false
  oauth2:
    base-url: http://192.168.99.100:30881
    realm: curie

logging.level.io.fairspace: DEBUG

security:
  oidc:
    required-authority: user-test
    clientId: test-pluto
    clientSecret: c108557d-9e9a-44e2-bb4d-d6f8cbef5860

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: false

zuul:
  routes:
    storage:
      url: http://192.168.99.100:31098/
    collections:
      url: http://localhost:8082/
    ui:
      url: http://192.168.99.100:30721/
  include-debug-header: true
