server.port: 5000
app:
  domain: http://localhost:5000
  forceHttps: false
  oauth2:
    base-url: http://localhost:5100
    realm: test

security:
  oidc:
    required-authority: user-ws
    clientId: ws-pluto
    clientSecret: 00000000-0000-0000-0000-000000000000

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: false

zuul:
  routes:
    storage:
      url: http://localhost:5110
    metadata:
      url: http://localhost:5120
    collections:
      url: http://localhost:5130
    ui:
      url: http://localhost:3000

  include-debug-header: true
