app:
  oauth2:
    base-url: http://localhost:5100
    realm: minikube

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest

ceres:
  url: "http://localhost:5120"

titan:
  url: "http://localhost:5110"

server:
  port: 5130
