# Some basic oAuth parameters that can easily be used in other places
app:
  connectTimeout: 500
  readTimeout: 6000
  oauth2:
    base-url: http://localhost:9080
    realm: keycloak
  metadata:
    base-url: http://fairspace.com
  rabbitmq:
    enabled: true
    topology:
      collections:
        exchange: "collections"
  cachingPeriod:
    collection: 60
    permission: 60

spring:
  application:
    name: Neptune
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://jaeger-collector.jaeger:9411/
  # Configuration for sql database which stores predicates and labels
  # Should be overridden in production
  datasource:
    url: "jdbc:h2:mem:neptune"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mvc:
    static-path-pattern: /static/**
  resources:
    cache:
      period: 604800s
      cachecontrol:
        max-age: 604800s
        cache-public: true

# Pointer to the Ceres service
ceres:
  url: "http://localhost:8001"

titan:
  url: "http://localhost:8002"

# Security configuration
security:
  oidc:
    jwk-key-set-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/certs
  urls:
    permitAll:
    - /actuator/health
    needsAuthentication:
    - /*
