language: java

jdk:
- oraclejdk8

env:
  global:
     - NODE_VERSION="11.2.0"
     - APPNAME="workspace"
     - ORG="fairspace"
     - ARTIFACT_BUILD_FILE=""
     - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
     - DEPLOYMENT_CONFIG_DIR="./.travis"
     - RELEASE_BRANCH="master"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"
     - RELEASE_CONTEXT="FairspaceDemoCluster"
     - SNAPSHOT_CONTEXT="FairspaceCICluster"
     - GIT_TAG_FILES_OVERRIDE="charts/workspace/Chart.yaml charts/workspace/values.yaml projects/"

     # DOCKER_PASSWORD=
     - secure: "FJTXKY792rdmQZ6DLU5Dlm1W9ZAmFwBFWEJDO4dLJySBO/clUUV0OfRkNX4OaachKUlRCFGxYbXaXCioYtMTVg54aD1d+hjBO5azPzUiT8V2mz2w3MkvxsvnvivziJtcSfol/PNHQdEK8qZhZ9IwdCnQM9LQ3YVwv9tkNpR//qNmUjA4ZdcbQrBLQ63wm/UX2vCo4D3/J24TfCJrmlu9AyoIAqiFsRczsQGixQLRzeRgwH3yFgACZrMt42ySrx4rL+Yi3Ro/ZftY+YrZPRs+wrObh++OmdzjQWXH4KBg8HTFEIJXYMOVnpG0OSdNO7j7oVS8qVRHJmFAG0VHrmSIMMbjU+3js3SVJxtwXRc3xEPJzKzhtyqGaQa5mr3pI1Q8YingcsEBEpWOh9zXBzJm1uh7JhgTgcEbBwQl12/SctMjejyAFFqVHhlSAEzuDBwTkXLiv6z6sF+SUpww8I6eKmQrJUN1HVPm9+n1nsBy1j3PIM0RmTAf+jZCuAMDg0Dg0dlY/in/Jz1k/QuFDbJ4ura4YBBQ315UDoki5rucDi2poxq9YoAaMpMouso9ilAwOms3guVaU/rgOHZsmIPqv2ccH6FEoOh2UeEq3RCGbprLAj88f2rcGNPaHNWRkeek31c+TI9JZPmeL5eh5tJ64cN+feVVk8lbqNWtR9VHRrI="

     # GITHUB_PASSWORD=....
     - secure: "l8Eug1n9WfHuNkrqrw0pLsxei2RsU1V+r3dty5YMDavWabBBkb5mEC9gQQ1LpPeHsLAFXxs6SXnahmZN6p9gj+yhWBnARXis7KFalMnXOyfa7PFAGmjT+rodtHy3B5CZLxcuN9wKFgDFtgrMc9xgsPN3fZEmloJKkmfGjHuGlNd0KACJFdZ16Y1pYl5AOoo0M6psyl+V1/13PSRPFxl88sOMfeyK3DbPUzF18zJ4EwQHxChJQr2oycvJl4ZhjoZ/6ivkaADySLZj0snXAbG5Rzch9lqwb/JkKbwAygXVwikCcT6YhQs5MjEbSQ1ZON0Pm2lPCH4IfP24dpraNlCn61YqGJR37WcWcGRlf+jlnjslJuJbynFlfqzzc1Blwm8DVV3hj4TfxwKSA5pba2ZHPR8TuV41pmfdLi4kOB0FZr+x8t0SdL2qHIPkCtQZ1/k/MCaTwUvS4SuURfeDI2b5Kbr7Eaoez0jdyE6jBRUhFP6Vehx22ZO5xbCsQ0pLXZdOSG8gRqHdp9b59mJgTZrx/Lycjrfy7VJzCM+n6MN4YHw8Vc5c5SHlH8XuJbUQkyjZdEFsGASHtzmq+LmZHIJ+GIbXxK9GWLXjG/3cePMXMrIuis9kHstpo1GLWHcOLVkQeZHyY8eo1iJrKKejT8LJ7/E2SzZwpZYl+9sCgKTr3e0="

     # NEXUS_PASSWORD=...
     - secure: "shZn2O8e9Cal6ZgzIRopKQuQXVP1DTf6MYm8/Llgh9RoN7jfzPzATYoKNcXaSWXCRpwGB8Uo4soDZovlfagCRueCY6D0/kymo+UqYo+Y1/8eylYbwd3fBGVuyorYNENxMiuqxIp2DDRq1i41bk3h3R4q5of+D+ZgRQUhCFUUrizga+zomuHq0uMBBJaVf9Ze2Bjg8YH+vXgd37fGgO4MxIsK4M9GsNsOrKkK0qEqAf8zvlsM16YIvcSFXWUi9V9htTNmXzbJiNKfvyKFnP+1YqgFwivFrYYdB8iDXlVAfYKslNZq85CQNG4q54rlNOloKZUdX5rsCP2+bPtLvWa7FpGPqN2KOYC5UcCwpIhBnG82gzM0e2YpIlo1p0PHWp9RgkzivmSiJLwRSUZKrWC2xq07wVS5y/CaPZx5nsAhVgSHJv2msc6AT6Pp5x+4xMtttrsh3IZ6EvO1AoDpoZ7ujJX5Hv+kC7VN0jGFkrhmyoRUyC7ntcqzJiKx80US+Uax4vpParPtVchDxO/kEcWRdOOah5NiIe8x+xu3ehxcPur4nAKrhU93oIoq3VhVeH+HvIFkHAq8lSlqjvl1HMrjbSVh8Shh+TQ0pv/srJp07L2zEIn0b5YGNQ+D0eNTbi5TtHOmSQGYr6VQfMFFiwydrBUNv15wJ5F+LfDftOA5qPA="

     # AZ_SERVICE_PRINCIPAL=... AZ_CLIENT_SECRET=... AZ_TENANT=...
     - secure: "qikLebpdlIdCRq4fGnC/EHzjSA9ZytjDAb38+q7Zly9Dzp27iLRIa3VZhmIT2yJ13aRvps14OqceY1sfbFtt6uzkoD42wTvMNbnbv4wqWtc676SkNt/1rppj9+aRpbuUGYa+D2VmBWrLPfEaIHSxYu5mg/l6js8SgCGbLhOCuhX3ZzrfwH8U7m8fq5ROJz3RBizdnGtTB1okrA6O/cdCVdR/1WoUyu0FJDvj1wEjc7EWSSlipm/GE+rYeKg1iQxqUF1+H9K/G5gQ8xNUCr+lJIHgnx+IO7o07Pt0buDik8S4hSoe57V3QeU1oAvfbpmubz9pSW4BsDOIzITbenZx+BQUbcpGxmtx4YU2lW6jmIgSE10D35hWBbPeoaOxDm1pPtGNKp4w1j+3XExdT7/j/OSEA/EhKh59nnP8J7qmGZrs1z68q6d50Dq+m9SxFRrG0bIHMO9NKrd5J7gnva2pnixQFkXeMr3/OK1ktmamf11a66OyGN+2WylbvP8n1CTK4RCmp6GOtLw4mjck1CDN0Jqq/DSW4gLU6VcmyJkSFLOksXAcTB+KhB/Z+yBX0bEskV9VyIeXryuzVnbqE36jJ5bLZUAU/9tsyiAmHuI9hc5pz2o+fu3Dje/zYZyqB7jMsuA9vZBMyNnpo+scunS7/ZD+5IvY+7l95Blu8xbiArc="

cache:
  directories:
  - $HOME/downloads
  - $HOME/.cache/yarn
  - $HOME/.gradle

notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      - secure: "rTnDQvuOaOy65rCsCtVkUzSIV3zThn3psFfg31Tm3G4BZlqlTAYCyiSJRClXFlWDcuMJGt+/BCFJsTnsKcTphfJ+a9/UeCveax92vCiLhC7Jae0z/wHKxkCwgeKOvwe5xPLAZbrNBPjWN82AwfZE+w0XkMb7gp8rYj9Nl09rDtOa63PF3uD7L+01WUaa/ch9V2VdLuAXt9BBE4LtClZs2596B+F32KTP4g5TKFLA8y4CUcDa2ggFoeQqswAbqdrcCrWLlSWvjzTfowlCqzPKKh3ei1bhj93Dv6jNpcmJU40Co2YGGkz//kCOCM8oMIx2byP5Ter36ZRT483LWbxDiiRVDX7ii1rosq7U1GbVcZx7wt6dXRLmiMqtSEam/acnwEYmTqmCGbcnWCAx7APeXym2SX643riAjGzJQr6TwqkcxtovT3Fmm7v+o3fJXILMaR+CX/rDlfHb3U/FD3PjtzDEy+4avBVA4JPU3DIfdCPrJ3DFRfPzviTCoDsAWcNOypRHfHMJ9Dbh0N3uXHD6TnQfqUHiB7dRgpdSFAjvpGYneL+TzgY/PP4j7O/GqdY6YvUtSbBeg1r3Bw4a7tv4KCA8YvjIRwt21K64Tcz9cubmnOwytI2GZTWN2/2pXucmnABa9EBHpYO2XfQ/5FnfVf48qWrtqGeqpG9XBrrNhNM="
    template:
      - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true

before_install:
  - nvm install $NODE_VERSION
  - export KUBE_CONFIG_ENC_KEY=$encrypted_5162cfbd2a53_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_5162cfbd2a53_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - export BUILD_SCRIPTS_DIR=$(pwd)/ci
  - source ./ci/setup_env.sh
  - 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT"; fi'
  - 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=demo KUBERNETES_CONTEXT="$RELEASE_CONTEXT"; fi'
  - 'if [[ "$SHOULD_RELEASE" ]]; then export OIDC_AUTH_VERSION=$VERSION; fi'

# This additional host is needed for the e2e tests to run properly
# against the docker-compose setup
addons:
  hosts:
  - keycloak

jobs:
  include:
    - stage: build
      name: Build projects (and run e2e test for a PR)
      script:
      - .travis/build.sh projects/oidc-auth
      - .travis/build.sh projects/callisto
      - .travis/build.sh projects/ceres
      - .travis/build.sh projects/mercury
      - .travis/build.sh projects/neptune
      - .travis/build.sh projects/pluto
      - .travis/build.sh projects/titan
      - .travis/build.sh projects/jupyterhub-hub
      - .travis/build.sh projects/jupyterhub-singleuser
      - 'if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then ci/docker/login.sh && .travis/pr/start-local-environment.sh && .travis/pr/run-e2e-tests.sh; fi'
    - stage: build
      name: Build helm charts
      install:
      - source charts/.travis/install.sh
      script:
      - charts/.travis/build.sh
    - stage: deploy
      if: branch IN (env(RELEASE_BRANCH), env(SNAPSHOT_BRANCH)) AND type != pull_request
      install:
        - source charts/.travis/install.sh
      script:
      - travis_wait ci/helm/deploy.sh
    - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
      stage: Versioning
      name: Set tag and update version
      script:
      - "ci/versioning/add_tag_to_git.sh"
      - "ci/versioning/set_next_version.sh"
    - stage: e2e test
      if: branch = env(SNAPSHOT_BRANCH) AND type != pull_request
      script:
      - 'cd projects/janus && .travis/build.sh'

