language: node_js

node_js:
  - "node"

os:
  - linux

env:
  global:
     - APPNAME="titan"
     - ORG="fairspace"
     - DOCKER_REPO="fairspace.azurecr.io"
     - CHART_REPO=" https://fairspace.github.io/helm-repo"
     - ARTIFACT_BUILD_FILE="package.json"
     - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
     - RELEASE_BRANCH="master"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"
     - HELM_VERSION="2.11.0"
# Azure Docker repository credentials:
# DOCKER_PASSWORD=....
     - secure: "Lszh0YCXtSb91q3x27Iaxttl6fI9xUWEx4nOX/9BHPH6E5D0RGHnW5pafX5ZRjU9kcN6sV7la7dHToY3NDzZ57lHTp8e2W2os6XkU6xRJsZTn4AjrHwyq/piV8oGtzCyFhEDjQm7HkX09+1AeciPByZ08EYLwg+LkAah4aE+4YSRio9AYGiPNYMDrMbwdeztCvugsOHwaDtiIdbGaTg51U6cBglGOyUFSa6SkPZH/FU/ITScuCk/aCX2l+E0IXKqnQQMm1TLngRiL+/BlZAQgn3+vmzSlsDq/xmkwsQX+uYtHwkN/GfggHkWitXxZZbHU0Vfn07gL9tC35SrW/zid1/50TdxUs53sjCQ67fSgkXOhqZDZaeaXb5U8zFeyUsJaaL+CQFWo3ib19MuGEFf1v1216CzuRfdYQ1L5aCfyB0ocbQhjRBiE5pjTQhNLdHTIXlrT9JPfVtVV/T8Ge0uRWm/1LLILSlMaSm2kVPIhhB3hYRK5Kqzcpv2yAd87y9wjBB4+JiX/nC9RL2WzA8GSayVvwzhBr3K2L7Rfby5wzK7Qqj3upRDvfR4kZQXbNmIhjxLa+cV7+IlPCI6QxK5HH9qKuQT7LlGFQsX1wyE/XlcZEeHdiXsC4HDskfMI/xgt+xW5IsTT1JCSzsZH+tMP1J2Uxi1oTv26ghBlJGkIiA="
# Github credentials:
# GITHUB_PASSWORD=....
     - secure: "Y9CKTHXuwA5yljO9SPK/t955D30tFzkW0Rq/c7tWmB3v8eoeRYrzHRhE2MFcUSZ5rATdjVZ8Jt0INeeS2KCmtqwhnKSUMghUhFAzqaIe/yabr9bWfUed29cq9GtJQEu8nlZgrxcpxCAT28dyYMRG2AUYCqGNImsVhXrSy6zcTW8kDaZE9mLyhURBSoCayr92cN6vaX2sT5L4Re1fTbSnyD4RlROOqpiRvMGWTdKq+McmSK17IRZEhElH/CrzsVl+xVC81X5zJsVbgHzENKSYHLZHbjGQx12f/dRL68zEvoN9yndrX0rDaj5jQ0P2/HWes4WKQlJFQIG+g52NsMkdypHhe3vSO08RHj2FGv2CzTsOGcYKPf1FWwOe0XN9NlJbbUhICesmtfqm0WgdZANi47n7LZFWop7de2dwD7+TP2RyJvQxUbG6uxhsVE8zXZLgGNSW0b04VkUfaxMzYRXa3fsv3KqOdwt/ztEQahYnERBiewvrUO/2epZbdV1d7K3peYYIVprrB6S7u+y89ij7vO5nx97sab0b8Qn4EJ47uezUQjbaNi4UGR8KbzCZ/SasfbHg8XmvhcK6miHKuhUM+NGU1wpuL9GPMjEqxGKfira83uQNAfL6OQN6Evd28TchOhmDGBFr+uLhdnPD5zB/rQ57QXiHtrSZ/PTKPgk11QE="

notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      - secure: "ZCsFGDF9FGF58WLLYCbbaIm4673PaHFviaYowYnU3Gm5AgDUARRSlW914oZEd5fr0y6+1MRBfzZ3c+Y9VvUDW/oh8wbPPMVxUfgvr1bZI7np4gnOV2VfHoqa2NStdN6J0O0gyuVJ+v+25H1aSfse95UAPdSkcMuPvH1Xo8BwgeD8+GLzNnnYxORY2QwJkcRWgfauj/oZSfI/P5LFkt5hbnWukKvQIlCbRzqkhHjShMLIs72OJjnClLK5x9oK4aowlIh9/wDiNJazr/Yw4oWskscnU1KLRzcYCAr8QpY+yMmdbNd1HusaAZb7h+86I6Xl8OU6w4jFClDtn7JwLUN1gSDQAPP50jYYQQ6NGoRDxqtlTr7y2vSIKCuunBieR/Xif5IA/cZop2cPG10hrKrBNCqjTLdVm/6V44duWckGtUPNJ3ln/v1OKLDGPvCimUGEqK+TRc07jzyJ8rl/9Hab6wy/kQHHjqpQeHaYn1wHRiGZ4BaGhEJy5eqm34rzw8RSluMlc9mRm0C3a6lQ35HJ2FDE0C+R4JBvildJ9/ouJ7UU6Y4uNZkGmgXW+7X6cizPIHDVC3wxUzhDYxlgFDyDfjKaJhw2TKmHEhT2Dto/NHqFj0BtW6YxZ3DxNBCUCOXCUkSflFLXqDTiHgNJhVMRIeenTWdpjhRT/LkKqu/Lq1k="
    template:
      - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true

before_install:
- git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci

before_script:
  - '[[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]] && export VERSION_POSTFIX="-SNAPSHOT" || true'
  - '[[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && export SHOULD_RELEASE=1 || true'
  - '[[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && export SHOULD_RELEASE=1 || true'
  - export CURRENTVERSION="$(cat VERSION)"
  - export VERSION="${CURRENTVERSION}${VERSION_POSTFIX}"
  - export CONTAINER_NAME="${DOCKER_REPO}/${ORG}/${APPNAME}:${VERSION}"
  - export NEWVERSION="$(./ci/versioning/nextversion.sh ${CURRENTVERSION})"

jobs:
  include:
  - stage: Build
    name: App and Docker image
    services:
    - docker
    cache:
      directories:
      - node_modules
    script:
    - ./ci/npm/tag.sh
    - ./ci/npm/build.sh
    - ./ci/docker/build.sh
    - '[[ $SHOULD_RELEASE ]] && ./ci/docker/release.sh || true'
  - stage: Build
    name: Helm chart
    install:
    - ./ci/helm/install_helm.sh
    - export PATH="$(pwd)/linux-amd64/:$PATH"
    - helm init --client-only
    script:
    - ./ci/helm/tag.sh
    - ./ci/helm/build.sh
    - '[[ $SHOULD_RELEASE ]] && ./ci/helm/release.sh || true'
  - # For release branch, update git with the new tag and update version
    if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
    stage: Versioning
    name: Set tag and update version
    script:
    - ./ci/npm/tag.sh
    - ./ci/helm/tag.sh
    - ./ci/versioning/add_tag_to_git.sh
    - ./ci/versioning/set_next_version.sh
  - if: branch = env(SNAPSHOT_BRANCH) AND type != "pull_request"
    stage: Trigger downstream
    name: Trigger workspace build
    install: skip
    script:
    - sh ./ci/trigger-travis/trigger-travis.sh --pro --branch dev $ORG workspace $TRAVIS_ACCESS_TOKEN
