language: java
jdk:
- oraclejdk8
os:
- linux
env:
  global:
  - APPNAME="ceres"
  - ORG="fairspace"
  - ARTIFACT_BUILD_FILE="build.gradle"
  - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
  - RELEASE_BRANCH="master"
  - SNAPSHOT_BRANCH="dev"
  - DOCKER_USERNAME="fairspace"
  - GITHUB_USERNAME="fairspace-ci"
  - HELM_VERSION="2.11.0"
  # DOCKER_PASSWORD = ...
  - secure: "HIv/qU0nGjBEwafbPGfWkS9sknOsJIcrUKLq4QBDBefNoCF3fTKq72hFzmyO0iizlzxuD5TZEZbbUnTiw3AuwO7qjhegIPcpeCLC/pOAOax10eIQVOW0ZKMRekQDt4nYm2aOmniycbwpR5BZv3pvul9ZSKrLvJ/Yk1Qsb+FIsLyjgPQVa8HTs8pfuKYkWXNgs9sBRaeeJ8AkWwq19RBrbnu0A7c5U9UNQz9NDxzT+Q/JQpuKTesL6d5UeoAWjjfqk/ysuztWiYYzU7uOAtaRllGL2SMQFSou0sS+DVAV3s9C/ScvVfffxcIJr/mdoHXENv34e99o1Svqt5a+p5mmaRrBiWsoYZz/fBk5k2yoa+WDO1fHBvv/5o67oc7JzD0aDjPsobuTWxpcVYCxQeTBziu/faEIVQ6AqKgd7WNRsZKavaE7wasTktdXzbTkDZKWJqzJpXIOmkkG5+6A+rrJNGALejxiuya2BhFGowet9LnyVtvqngr88QugDYxJFO1eYQHjekfJxwAB3CKDVDkZobEITNEt42H4xK92FVcFSJ4vC2oyqOG/ZuEequO9nJ27tdkhLEhNY6RIqFlcsLjHzWpLcZDAYdm6Vfk/arF1wEF94fSungJHq+T/UCoSDCHzylDcji56dYzeOha+6HhY7BgkKFv2VrqT82XSqx8gLww="
  # GITHUB_PASSWORD = ...
  - secure: "pDMIBUcis36A8Ych42Bfr1bMZDf6Il+dU38+HOKzU0e/MiYsUsD7dpazhqh/zD2qaNrHnPIwIdvfOYGHunsOtZAxhLSFYBcfrLEDX5AkYwUVVIAgXo0+aLVtktiPy730qdtDxfl481RD21nLbA8KGh8vxOUClfSiWAAnzc9wf75idRY5WLhBWPmHcYEItliKrbjBI0HkwlD+/z8p4Nm9lNnetC5odFbCLhFHRZiLIfdM2gNdJhStLM35ZMQteAywbLUO1nmzlj7wfhCt5tPXcIkrjHhIB/hjc718vmKBxtXWPcI7V0o+4+4omTXw72xR8JkdvpWQljhYEy8Nr07F3ATkZXY2jMXQMQk/FjzZRpzXX6NdF+HQY1xfCZPbNXLgFhtVA35BWzy+9ZeggZ52DpqeQnyHxEYoPR/11JxejucYnAgsLhnaoWs9cpJpYuEMoFpHWaRBBln/Lg76GXOb8G8sB6h0hi+SGaFKJj4ImOrc6qLJjqX3G4rbDgdfAnxvyuuwXkrMLkIvxHpcuTNj7pCtA29XF9KBbynS2W0QM2QZwvq+q/5FV+DPP5qlwpDWVGtY0eQ0bDICLPW6P2ssA7R326CFR0kjXEKMDawoav1LY4u9GQ+T3w0ByNx7jbCWHF/AtDC6VFAkr3TInk/fUMhMuPAYkRIPq2becCWSR88="
  # Azure credentials
  - secure: "jiKkzL43ik/Ek60dvl3+aw3kq7CzEBsMAqjxh4MpcepQaliFlMmOImQgCrARXIEKwc+WGSjzg358sl0iMfVUCjbnUIq25ww3p/PeIfolrBiexAsx2uUu+st2eCbZmT0E8fT+w2+sVjoLkKyqHWIlVMelc1b3TfyOkYG6YKm39uvqWjYkeKZbSgYGoFpOgMxoC0VnNjX0cPmynt88XraYkAtA2eXSgggXKT79WhQk+8S64EKqbJZSIrQ7s8QZD9+Ag0ITEaFy9EzsUHc+zdHiVNbHa5xLRzeHC7fpmbIdDbJ9QHU+js3i8RBcHLdyHnTSxJBsdNWtkB0267/EeSTCQUoOnMwwAEJcsshLPca/fnfekFuLMpzfnHc2JNpHDm8WTTBd/CbDR5amz7dsaV14FL07tESo96GZGXeCT/E5CLgvWvT41YH5PqExvZ+vZKxW6z3WDCI8AvvEchxl5FeTDfOyxlmFJDwV/RJapBVjZPdceq8v1z3zyKOmB3Fdo0DlqNNoon01KflKNc/Z0bQ4dZv+Bdx0h15AJxfScwu29AZFtJMb0tUU7VmPALSpERuN/tzwOqOwQXqUHcqgBJTCgCt3kOoOs5qP6NExZRkccJh3M0/mta8eI8cyh083ngRMce9XhZt7TBHCGw7EkdYLBPogk3raBSDwuKhqvZx+D9Q="
notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      secure: "uFDPC2zPZHbeuwqwC0nXGywtS+aX73Gy2VUm5XvuVkcSal/W4OQHUIEE0L1p4iv52LeqP2sYefxY3KTg2guah3+5rbykTTCONtfQIs0Lk7VQzZ534MtWgARUTVIbt3krxoIrPWX2Svxrqm6dg/AhFQp7orcAgq4y5OUax/dJmWCtBwTnRIG6ryBk6rG70c7OUH5u4Ql6/TLtPECwTl0h5Jyo3E6ihdPF7UIHbAL8K3E/r9RyseQGKvwldI3VI6x+d4pTfOpiebJ4Ba8vnioKh4DXv0IxjPwUxI7vCN2neWVrlezpMdMpF+F1tiCd7yB840lMRE9OVacJ+DVp2PwbYux+sQ8xayaaiksR00VPSsdlUETOg7YoJIRVSmiyyi1T4KejTTZS7B7/kEFOWVTAvVkRiNCRK0csGWI+8r/NzoBAFm4LyzNXqn3bX+Qd3sveS/1qEdahgaEiN55z6OtbDDp2hIlRzWkNoWPUjTjlZ3nKyzN1iht3lQp7OVhnQAeSTdlVC6bezNDHkuDJqA8nnEI0dxL3t4dfgghueUQkViHdN570hfw+1rsMj7eS5uDl7KPV60vYlcqCYxf5pPSzW+ndaaqwf2Q6Jta/hUV6WE+8iepYxW6Wo2aXTu3hK0niaDp+sEf95A/T/Uz9g5sg1Wj8bE7N3HcuH6ew+Rsim4w="
    template:
    - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} -
      <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true

before_install:
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - source ./ci/setup_env.sh

jobs:
  include:
  - stage: Build
    name: App and Docker image
    services:
    - docker
    cache:
      directories:
      - "$HOME/.gradle"
    script:
    - ./ci/gradle/tag.sh
    - ./ci/gradle/build.sh
    - ./ci/docker/build.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/docker/release.sh; fi'
  - stage: Build
    name: Helm chart
    install:
    - source ./ci/helm/install_helm.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/az/install.sh && ./ci/az/login.sh; fi'
    script:
    - ./ci/helm/tag.sh
    - ./ci/helm/add_pod_annotations.sh
    - ./ci/helm/build.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/helm/release.sh; fi'
  - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
    stage: Versioning
    name: Set tag and update version
    script:
    - "./ci/versioning/add_tag_to_git.sh"
    - "./ci/versioning/set_next_version.sh"
  - if: branch = env(SNAPSHOT_BRANCH) AND type != "pull_request"
    stage: Trigger downstream
    name: Trigger workspace build
    install: skip
    script:
    - sh ./ci/trigger-travis/trigger-travis.sh --pro --branch dev $ORG workspace $TRAVIS_ACCESS_TOKEN
