kind: Secret
apiVersion: v1
metadata:
  name: testuser-secret
type: Opaque
data:
{{- if .Values.workspace.testuser.username }}
  username: {{ .Values.workspace.testuser.username | b64enc | quote }}
{{- else }}
  username: {{ printf "test-%s" .Values.workspace.name | b64enc | quote }}
{{- end }}
{{- if .Values.workspace.testuser.password }}
  password: {{ .Values.workspace.testuser.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}