apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mercury.fullname" . }}
  labels:
    app: mercury
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |-
    {
      "urls": {
        "storage": "{{ .Values.mercury.urls.storage }}"
      }
    }

