apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "mercury.fullname" . }}-server
    labels:
        app: mercury
        chart: {{ template "workspace.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    config.yaml: |-
      urls:
        keycloak: {{ template "keycloak.baseUrl" . }}/auth/admin/realms/
        elasticsearch: {{ template "elasticsearch.baseurl" . }}
        workspaces:
          {{ toYaml .Values.mercury.workspaces }}
      keycloak:
        realm: {{ .Values.external.keycloak.realm }}

