# Default values for vre.
# This is a YAML-formatted file.

# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
imagePullSecrets: {}

# Set specific workspace name. Defaults to release name
# Please note that if this is set, also set it for pluto in `pluto.workspace.name`
nameOverride:

# Hyperspace that this workspace is connected to
# Please note that pluto also has to know about the
# keycloak baseUrl and realm, see the pluto configuration
hyperspace:
    tls: true
    domain:
    locationOverrides:
        keycloak:
        rabbitmqhostname: hyperspace-rabbitmq.hyperspace.svc.cluster.local

    # TODO: determine better way to handle keycloak credentials
    # Keycloak credentials are needed to setup the workspace (e.g. users, clients)
    # in keycloak. Please note that this is not a sustainable way of doing, due
    # to the sensitive nature of these parameters
    #
    # We could either:
    # - have the hyperspace setup keycloak itself, when creating a new workspace
    # - use temporary credentials for setting up these users
    # - ...
    keycloak:
        username:
        password:
        realm:
        clientSecret:

    rabbitmq:
      username:
      password:

# Setup ingress for workspace components
workspace:
    ingress:
        enabled: true
        domain:
        annotations:
          pluto:
            kubernetes.io/ingress.class: nginx
          storage:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 10g
            nginx.ingress.kubernetes.io/rewrite-target: /zuul
          jupyter:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns

    testuser:
        password: fairspace123
    coordinator:
        password: fairspace123

    # Scripts for setting up keycloak for a workspace
    configurationScripts:
      keycloak:
        enabled: true
        image: fairspace.azurecr.io/fairspace/keycloak-configuration:0.1.0
        pullPolicy: IfNotPresent
      rabbitmq:
        enabled: true
        image: fairspace.azurecr.io/fairspace/rabbitmq-configuration:0.1.0-SNAPSHOT
        pullPolicy: IfNotPresent

# Generic settings for tracing
tracing:
  enabled: true
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

services:
  jupyterhub:

#####################################################################
# Specific settings for Pluto subchart
# Default configuration points to titan, mercury and neptune
# in the same workspace
#####################################################################
pluto:
  replicaCount: 1
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%
  image:
    image: fairspace.azurecr.io/fairspace/pluto
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  probePath: /actuator/health
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  rabbitmq:
    vhost:
    username:
    password:

  # Reference to the workspace for informational purposes
  # These values default to the release name and chart version
  # The name is also used in the default setting for requiredAuthority and clientId
  workspace:
    name:
    version: 0.0.0-RELEASEVERSION

  # Keycloak configuration for authentication
  keycloak:
    client:
      id:
      secret:
    redirectAfterLogoutUrl: https://fairspace.com
    requiredAuthority:

  # Where to find the backends for this proxy
  backends:
    ui:
    metadata:
    storage:
    collections:

#####################################################################
# Specific settings for Ceres subchart
#####################################################################
ceres:
  replicaCount: 1
  rollingUpdate:
    maxSurge: 0%
    maxUnavailable: 100%
  image:
    image: fairspace.azurecr.io/fairspace/ceres
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent

  service:
    name: ceres
    type: ClusterIP
    externalPort: 80
    internalPort: 8080

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

  probePath: /actuator/health
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  ## Persist data to a persistent volume
  persistence:
    enabled: true

    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:

    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 512Mi
    subPath: "ceres-db"
    mountPath: /data/ceres

  rabbitmq:
    vhost:
    username:
    password:

#####################################################################
# Specific settings for Neptune subchart
#####################################################################
neptune:
  replicaCount: 1

  image:
    image: fairspace.azurecr.io/fairspace/neptune
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  probePath: /actuator/health
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  rabbitmq:
    vhost:
    username:
    password:

  ceres:
    url:

  titan:
    url:

#####################################################################
# Specific settings for Titan subchart
#####################################################################
titan:
  replicaCount: 1
  rollingUpdate:
    maxSurge: 0%
    maxUnavailable: 100%
  image:
    image: fairspace.azurecr.io/fairspace/titan
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    name: titan
    type: ClusterIP
    externalPort: 80
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m

  # Authentication parameters
  rabbitmq:
    exchange: storage
    vhost:
    username:
    password:
  auth:
    enabled: true
    tokenUrl:
    clientId:
  persistence:
    enabled: true
    mountPath: /data
    rootPath: /data

    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:

    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 512Mi
    subPath: titan

  collections:
    collectionUrl:

#####################################################################
# Specific settings for Callisto subchart
#####################################################################
callisto:
  replicaCount: 1

  image:
    image: fairspace.azurecr.io/fairspace/callisto
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  terminationGracePeriodSeconds: 10

  rabbitmq:
    vhost:
    username:
    password:

  # Please note that mail settings are copied into the application.yaml configuration
  # file for spring. This means you can add any mail settings accepted by Spring mail
  # See e.g. https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-email.html
  # for more information.
  mail:
    host:
    port:
    username:
    password:

  app:
    mail:
      from: info@fairspace.com

#####################################################################
# Specific settings for Mercury subchart
#####################################################################
mercury:
  replicaCount: 1
  image:
    image: fairspace.azurecr.io/fairspace/mercury
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  probePath: /
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  urls:
    storage:

#####################################################################
# Specific settings for JupyterHub subchart
#####################################################################
jupyterhub:
  auth:
    type: custom
    custom:
      className: oauthenticator.openid.OpenIDConnectOAuthenticator
      config:
        enable_auth_state: True
        client_id:
        client_secret:
        openid_url:
        session_url:
    scopes:
      - offline_access
  singleuser:
    image:
      name: fairspace.azurecr.io/fairspace/jupyterhub-singleuser
      tag: RELEASEVERSION
    defaultUrl: "/lab"
    extraEnv:
      WORKSPACE_URL:
  hub:
    image:
      name: fairspace.azurecr.io/fairspace/jupyterhub-hub
      tag: RELEASEVERSION
    ingress:
      enabled: false
    extraEnv:
      JUPYTERHUB_CRYPT_KEY:
    extraConfig:
      customConfig: |
        c.KubeSpawner.cmd = ['/start']
        c.KubeSpawner.singleuser_privileged = True
        c.Authenticator.auto_login = True
  proxy:
    # The JupyterHub chart requires this value to be set here with the same
    # length as the actual values
    # Ensure to override this value with a 64-character hex string when installing
    secretToken: "0000000000000000000000000000000000000000000000000000000000000000"

#####################################################################
# Specific settings for databases
#####################################################################
postgresql_neptune:
  postgresqlUsername: postgres
  postgresqlPassword: test123
  postgresqlDatabase: neptune
  nameOverride: postgresql-neptune

postgresql_ceres:
  postgresqlUsername: postgres
  postgresqlPassword: test123
  postgresqlDatabase: ceres
  nameOverride: postgresql-ceres

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: {}
