# Default values for vre.
# This is a YAML-formatted file.

# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
fairspaceImagePullSecret:

# Set specific workspace name. Defaults to release name
# Please note that if this is set, also set it for pluto in `pluto.workspace.name`
nameOverride:

# Hyperspace that this workspace is connected to
# Please note that pluto also has to know about the
# keycloak baseUrl and realm, see the pluto configuration
hyperspace:
    tls: true
    domain:
    locationOverrides:
        keycloak:
        rabbitmqhostname: hyperspace-rabbitmq.hyperspace.svc.cluster.local

    # TODO: determine better way to handle keycloak credentials
    # Keycloak credentials are needed to setup the workspace (e.g. users, clients)
    # in keycloak. Please note that this is not a sustainable way of doing, due
    # to the sensitive nature of these parameters
    #
    # We could either:
    # - have the hyperspace setup keycloak itself, when creating a new workspace
    # - use temporary credentials for setting up these users
    # - ...
    keycloak:
        username:
        password:
        realm:
        clientSecret:

    rabbitmq:
      username:
      password:

# Setup ingress for workspace components
workspace:
    ingress:
        enabled: true
        domain:
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns

    testuser:
        password: fairspace123
    coordinator:
        password: fairspace123

    # Scripts for setting up keycloak for a workspace
    configurationScripts:
      keycloak:
        image: fairspace.azurecr.io/fairspace/keycloak-configuration:0.1.0
        pullPolicy: IfNotPresent
      rabbitmq:
        image: fairspace.azurecr.io/fairspace/rabbitmq-configuration:0.1.0-SNAPSHOT
        pullPolicy: IfNotPresent

# Specific settings for pluto
# Default configuration points to titan, mercury and neptune
# in the same workspace
pluto:
  overrides:
    keycloak:
      client:
        secretNamePostfix: oauth-client

  keycloak:
    baseUrl:
    realm:
    redirectAfterLogoutUrl: https://fairspace.com

  rabbitmq:
    hostname:
    vhost:
    username:
    password:

  services:
    jupyter:

  workspace:
    version: 0.0.0-RELEASEVERSION

# Specific settings for Ceres subchart
ceres:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 512Mi
    subPath: "ceres-db"
    mountPath: /data/ceres

  rabbitmq:
    hostname:
    vhost:
    username:
    password:

  app:
    oauth2:
      baseUrl:
      realm:
    metadata:
      baseUrl:

# Specific settings for Neptune subchart
neptune:
  rabbitmq:
    hostname:
    vhost:
    username:
    password:

  app:
    oauth2:
      baseUrl:
      realm:
    metadata:
      baseUrl:

# Specific settings for Titan subchart
titan:
  rabbitmq:
    hostname:
    vhost:
    username:
    password:
  auth:
    tokenUrl:
    clientId:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 512Mi
    subPath: "titan"
    mountPath: /data


# Specific settings for JupyterHub subchart
jupyterhub:
  auth:
    type: custom
    custom:
      className: oauthenticator.openid.OpenIDConnectOAuthenticator
      config:
        enable_auth_state: True
        client_id:
        client_secret:
        openid_url:
        session_url:
    scopes:
      - offline_access
  singleuser:
    image:
      name: fairspace.azurecr.io/fairspace/jupyterhub-singleuser
      tag: 0.3.1
    defaultUrl: "/lab"
    extraEnv:
      WORKSPACE_URL:
  hub:
    image:
      name: fairspace.azurecr.io/fairspace/jupyterhub-hub
      tag: 0.3.2
    ingress:
      enabled: false
    extraEnv:
      JUPYTERHUB_CRYPT_KEY:
    extraConfig:
      customConfig: |
        c.KubeSpawner.cmd = ['/start']
        c.KubeSpawner.singleuser_privileged = True
        c.Authenticator.auto_login = True
  proxy:
    # The JupyterHub chart requires this value to be set here with the same
    # length as the actual values
    # Ensure to override this value with a 64-character hex string when installing
    secretToken: "0000000000000000000000000000000000000000000000000000000000000000"

