# Default values for vre.
# This is a YAML-formatted file.

# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
imagePullSecrets: {}

# Set specific fairspace name. Defaults to release name
nameOverride:

# External dependencies for running the fairspace
external:
  # TODO: determine better way to handle keycloak credentials
  # Keycloak credentials are needed to setup the fairspace (e.g. users, clients)
  # in keycloak. Please note that this is not a sustainable way of doing, due
  # to the sensitive nature of these parameters
  #
  # We could either:
  # - have the hyperspace setup keycloak itself, when creating a new fairspace
  # - use temporary credentials for setting up these users
  # - ...
  keycloak:
    baseUrl:
    username:
    password:
    loginRealm: master
    realm:
    clientSecret:
    serviceAccount:
      username: fairspace-service-account
      password:

  elasticsearch:
    enabled: true
    rest:
      scheme: http
      host:
      port: 9200
    transport:
      host:
      port: 9300

#####################################################################
# Specific settings for ElasticSearch
#####################################################################
elasticsearch:
  enabled: true
  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard
  client:
    resources:
      requests:
        memory: "800Mi"
        cpu: 0.1
      limits:
        memory: "1024Mi"
        cpu: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
  data:
    exposeHttp: true
    resources:
      requests:
        memory: "1600Mi"
        cpu: 0.1
      limits:
        memory: "2048Mi"
        cpu: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
  master:
    resources:
      requests:
        memory: "800Mi"
        cpu: 0.1
      limits:
        memory: "1024Mi"
        cpu: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"

# Setup ingress for fairspace components
fairspace:
    name: "fairspace"
    description: "Fairspace"
    ingress:
        enabled: true
        domain:
        annotations:
          saturn:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 10g
          docs:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
    keycloak:
      # Roles defining the keycloak roles for this fairspace
      roles:
        user:
        coordinator:
        datasteward:
        sparql:

      # Groups to retrieve a list of users from
      groups:
        user:

    # Scripts for setting up keycloak for a fairspace
    configurationScripts:
      keycloak:
        enabled: true
        dockerRepository: eu.gcr.io
        image: fairspace-207108/keycloak-configuration
        configurationScriptsTag: 0.1.8
        pullPolicy: IfNotPresent
        resources:
            requests:
                cpu: "50m"
                memory: "512Mi"
            limits:
                cpu: "500m"
                memory: "2048Mi"

    enableExperimentalFeatures: false

# Generic settings for tracing
tracing:
  enabled: false
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

services:
  jupyterhub:
  cbioportal:

#####################################################################
# Specific settings for Saturn subchart
#####################################################################
saturn:
  auth:
    enableBasicAuth: true
  persistence:
    files:
      ## A manually managed Persistent Volume and Claim
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      size: 50Gi
    database:
      size: 50Gi
  image:
    image: eu.gcr.io/fairspace-207108/projects
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  initContainer:
    image: alpine:3.9
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10
  ## Creates a custom storage class which can be used in persistence section
  customStorageClass:
      create: false
      name:
      type: pd-standard
      provisioner:
      allowVolumeExpansion: true
      reclaimPolicy: Delete
  bulkTransactions: true
  # See Apache Jena TDB2 documentation
  storeParams:
    tdb.file_mode: "mapped"
    tdb.block_size: 8192
    tdb.block_read_cache_size: 5000
    tdb.block_write_cache_size: 1000
    tdb.node2nodeid_cache_size: 200000
    tdb.nodeid2node_cache_size: 750000
    tdb.node_miss_cache_size: 1000
    tdb.nodetable: "nodes"
    tdb.triple_index_primary: "SPO"
    tdb.triple_indexes:
      - "SPO"
      - "POS"
      - "OSP"
    tdb.quad_index_primary: "GSPO"
    tdb.quad_indexes:
      - "GSPO"
      - "GPOS"
      - "GOSP"
      - "POSG"
      - "OSPG"
      - "SPOG"
    tdb.prefixtable: "prefixes"
    tdb.prefix_index_primary: "GPU"
    tdb.prefix_indexes:
      - "GPU"
  mail:
    mail.from: info@fairspace.io
    mail.user: user
    mail.password: password
    mail.transport.protocol: smtp
    mail.smtp.auth: true
    mail.smtp.host: host
    mail.smtp.port: 587
    mail.smtp.starttls.enable: true
  vocabulary: |
    @prefix fs: <http://fairspace.io/ontology#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix sh: <http://www.w3.org/ns/shacl#> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix schema: <http://www.schema.org/> .
    @prefix foaf: <http://xmlns.com/foaf/0.1/> .
    @prefix fhir: <http://hl7.org/fhir/STU3/> .
    @prefix dash: <http://datashapes.org/dash#> .
    @prefix curie: <https://curie.org/dontology#> .

    ########################
    ###   User Shapes    ###
    ########################

    ## Augmented system class shapes
      fs:File sh:property
      [
      sh:name "Is about person" ;
      sh:description "Persons that are featured in this collection." ;
      sh:class foaf:Person ;
      sh:path curie:aboutPerson
      ],
      [
      sh:name "Is about biological sample." ;
      sh:description "Materials that are featured in this collection." ;
      sh:class curie:BiologicalSample ;
      sh:path curie:aboutMaterial
      ],
      [
      sh:name "Analysed by" ;
      sh:description "The files associated to the analysis" ;
      sh:class curie:Analysis ;
      sh:maxCount 1 ;
      sh:path curie:associatedAnalysis
    ] .

      ## User class Shapes

      curie:Person a rdfs:Class, sh:NodeShape ;
      sh:closed false ;
      sh:description "A person that is subject of research." ;
      sh:name "Person" ;
      sh:ignoredProperties ( rdf:type owl:sameAs ) ;
      sh:property
      [
      sh:name "Gender" ;
      sh:description "The gender of the patient" ;
      sh:in (
      "Male"
      "Female"
      "Unknown"
      "Other"
      ) ;
      sh:maxCount 1 ;
      sh:path fhir:AdministrativeGender
      ],
      [
      sh:name "Age of death" ;
      sh:description "The age at which this person has died" ;
      sh:datatype xsd:date ;
      sh:maxCount 1 ;
      sh:path curie:ageOfDeath
      ],
      [
      sh:name "Patient Identifier" ;
      sh:description "The identifier of the patient" ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      sh:path curie:patientIdentifier
      ],
      [
      sh:name "Event" ;
      sh:description "Tumor pathology events for this patient" ;
      sh:class curie:TumorPathologyEvent ;
      sh:path curie:hasEvent
      ],
      [
      sh:name "Gave consent" ;
      sh:description "" ;
      sh:class <PersonConsent> ;
      sh:path <gaveConsent>
      ],
      [
      sh:name "Label" ;
      sh:description "Human readable label for this resource." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      fs:importantProperty true ;
      sh:path rdfs:label;
      sh:order 0
      ],
      [
      sh:name "Description" ;
      sh:description "Human friendly description." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      sh:path rdfs:comment
    ] .

      curie:PersonConsent a rdfs:Class, sh:NodeShape ;
      sh:closed false ;
      sh:description "A research consent given by person." ;
      sh:name "Person Consent" ;
      sh:ignoredProperties ( rdf:type owl:sameAs ) ;
      sh:property
      [
      sh:name "Consent for specific project" ;
      sh:description "" ;
      sh:class curie:ResearchProject ;
      sh:path curie:isProjectConsent
      ],
      [
      sh:name "Consent authorizes" ;
      sh:description "The samples that is authorized with this consent" ;
      sh:class curie:BiologicalSample ;
      sh:path curie:authorizes
      ],
      [
      sh:name "Is consent of" ;
      sh:description "" ;
      sh:class foaf:Person ;
      sh:maxCount 1 ;
      sh:path curie:isConsentOf
      ],
      [
      sh:name "Label" ;
      sh:description "Human readable label for this resource." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ; ;
      fs:importantProperty true ;
      sh:path rdfs:label;
      sh:order 0
      ],
      [
      sh:name "Description" ;
      sh:description "Human friendly description." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      sh:path rdfs:comment
    ] .

      curie:ResearchProject a rdfs:Class, sh:NodeShape ;
      sh:closed false ;
      sh:description "A research project." ;
      sh:name "Research Project" ;
      sh:ignoredProperties ( rdf:type owl:sameAs ) ;
      sh:property
      [
      sh:name "Project Code" ;
      sh:description "Specific project code." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      sh:path curie:projectCode
      ],
      [
      sh:name "Investigation Nature" ;
    sh:description "choose between: basic research, biomedical research, clinical trial, medical diagnosis" ;
      sh:in (
      "basic research"
      "biomedical research"
      "clinical trial"
      "medical diagnosis"
      ) ;
      sh:path <investigationNature>
    ],
      [
        sh:name "Project Manager" ;
          sh:description "Project manager" ;
          sh:datatype xsd:string ;
          dash:singleLine true ;
          sh:path curie:projectManager
      ],
      [
        sh:name "Has associated collections" ;
          sh:description "Collections that are related to this project." ;
          sh:class fs:Collection ;
          sh:path curie:hasCollection
      ],
      [
        sh:name "Person consent" ;
          sh:description "" ;
          sh:class curie:PersonConsent ;
          sh:path curie:hasPersonConsent
      ],
      [
        sh:name "Label" ;
          sh:description "Human readable label for this resource." ;
          sh:datatype xsd:string ;
          sh:maxCount 1 ;
          dash:singleLine true ;
          fs:importantProperty true ;
          sh:path rdfs:label;
          sh:order 0
      ],
      [
        sh:name "Description" ;
          sh:description "Human friendly description." ;
          sh:datatype xsd:string ;
          sh:maxCount 1 ;
          sh:path rdfs:comment
      ] .

      curie:TumorPathologyEvent a rdfs:Class, sh:NodeShape ;
      sh:closed false ;
      sh:description "Description for osiris:TumorPathologyEvent" ;
      sh:name "Tumor Pathology Event" ;
      sh:ignoredProperties ( rdf:type owl:sameAs ) ;
      sh:property
      [
      sh:name "Neoplasm Event" ;
      sh:description "The type of tumor event." ;
      sh:in (
      "primary tumor"
      "local relapse"
      "metastatic relapse"
      ) ;
      sh:maxCount 1 ;
      sh:path curie:EventType
      ],
      [
      sh:name "Neoplasm Event Start Date" ;
      sh:description "The start date of the tumor event" ;
      sh:datatype xsd:date ;
      sh:maxCount 1 ;
      sh:path curie:eventStartDate
      ],
      [
      sh:name "Neoplasm Event End Date" ;
      sh:description "The end date of the tumor event" ;
      sh:datatype xsd:date ;
      sh:maxCount 1 ;
      sh:path curie:eventEndDate
      ],
      [
      sh:name "Neoplasm diagnosis date" ;
      sh:description "The date of tumor diagnosis" ;
      sh:datatype xsd:date ;
      sh:maxCount 1 ;
      sh:path curie:diagnosisDate
      ],
      [
      sh:name "Event is analysed by" ;
      sh:description "Analyses associated with this tumor pathology event" ;
      sh:class  curie:Analysis ;
      sh:path curie:isAnalysedBy
      ],
      [
      sh:name "Event subject" ;
      sh:description "The patient associated with this event" ;
      sh:class foaf:Person ;
      sh:maxCount 1 ;
      sh:path curie:eventSubject
      ],
      [
      sh:name "Event parentage" ;
      sh:description "The tumor events could be linked to others as a chain. For example, a primary tumor event could be linked to a local relapse and then a metastatic relapse." ;
      sh:class curie:TumorPathologyEvent ;
      sh:path curie:isLinkedTo
      ],
      [
      sh:name "Label" ;
      sh:description "Human readable label for this resource." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      fs:importantProperty true ;
      sh:path rdfs:label;
      sh:order 0
      ],
      [
      sh:name "Description" ;
      sh:description "Human friendly description." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      sh:path rdfs:comment
    ] .

      curie:BiologicalSample a rdfs:Class, sh:NodeShape ;
      sh:closed false ;
      sh:description "Description for osiris:BiologicalSample" ;
      sh:name "Biological Sample" ;
      sh:ignoredProperties ( rdf:type owl:sameAs ) ;
      sh:property
      [
      sh:name "Collect Date" ;
      sh:description "The collect date of the biological sample" ;
      sh:datatype xsd:date ;
      sh:maxCount 1 ;
      sh:path curie:collectDate
      ],
      [
      sh:name "Tumor Cellularity" ;
      sh:description "The percentage of tumor cells in the biological sample (pathological measure)" ;
      sh:datatype xsd:integer ;
      sh:maxCount 1 ;
      sh:path curie:tumorCellularity
      ],
      [
      sh:name "Sample is authorized by" ;
      sh:description "The relevent consent" ;
      sh:class curie:PersonConsent ;
      sh:maxCount 1 ;
      sh:path curie:isAuthorizedBy
      ],
      [
      sh:name "Sample is child sample of" ;
      sh:description "The biological sample has been extracted from this parent sample" ;
      sh:class curie:BiologicalSample ;
      sh:path curie:isChildOf
      ],
      [
      sh:name "Label" ;
      sh:description "Human readable label for this resource." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      fs:importantProperty true ;
      sh:path rdfs:label;
      sh:order 0
      ],
      [
      sh:name "Description" ;
      sh:description "Human friendly description." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      sh:path rdfs:comment
    ] .

      curie:Analysis a rdfs:Class, sh:NodeShape ;
      sh:closed false ;
      sh:description "Description for Analysis" ;
      sh:name "Analysis" ;
      sh:ignoredProperties ( rdf:type owl:sameAs ) ;
      sh:property
      [
      sh:name "Analysis code" ;
      sh:description "The analysis run identifier" ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      sh:path curie:analysisCode
      ],
      [
      sh:name "Analytic pipeline code" ;
      sh:description "Identifier of the pipeline used into the analysis (unique in the center)" ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      sh:path curie:analyticPipelineCode
      ],
      [
      sh:name "Number of break points" ;
      sh:description "Calculated number of break points in genomic profile" ;
      sh:datatype xsd:integer ;
      sh:maxCount 1 ;
      sh:path curie:numberOfBreakPoints
      ],
      [
      sh:name "Analysis files" ;
      sh:description "The analysis linked to the files" ;
      sh:class fs:File ;
      sh:path curie:associatedFiles
      ],
      [
      sh:name "Label" ;
      sh:description "Human readable label for this resource." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      dash:singleLine true ;
      fs:importantProperty true ;
      sh:path rdfs:label;
      sh:order 0
      ],
      [
      sh:name "Description" ;
      sh:description "Human friendly description." ;
      sh:datatype xsd:string ;
      sh:maxCount 1 ;
      sh:path rdfs:comment
    ] .


# Settings for the documentation container
docs:
  nameOverride:
  replicaCount: 1
  image:
    image: eu.gcr.io/fairspace-207108/docs
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  probePath: /
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 60

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: {}
