# Default values for Gradle projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker-registry.jx.test.fairdev.app/fairspace/pluto
  tag: 0.1.16
  pullPolicy: IfNotPresent
service:
  name: pluto
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 400m
    memory: 768Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

# Reference to the workspace
workspace:
  name:

# Keycloak configuration for authentication
keycloak:
  baseUrl:
  client:
    id:
    secret:
  realm:
  redirectAfterLogoutUrl: https://fairspace.com
  requiredAuthority:

# Where to find the backends for this proxy
backends:
  mercury: http://mercury
  neptune: http://neptune
