{{- if .Values.fairspace.configurationScripts.keycloak.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-keycloak-config-map"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  redirect.urls: |-
    {{ template "fairspace.url" . }}/*
    {{ template "jupyter.url" . }}/*
{{- end -}}
