port: 8080
jena:
  datasetPath: data/db
  transactionLogPath: data/log
  vocabularyURI: http://fairspace.io/vocabulary#
auth:
  authEnabled: false
  jwksUrl: https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/certs
  jwtAlgorithm: RS256

