saturn:
  port: 8080
  datasetPath: data/db
  transactionLogPath: data/log
  vocabularyURI: http://fairspace.io/vocabulary#
  authEnabled: false
  authServerUrl: none
  authRealm: none
  authRole: none
