saturn:
  port: 8080
  datasetPath: data/db
  transactionLogPath: data/log
  vocabularyURI: http://fairspace.io/vocabulary#
  authEnabled: false
  jwksUrl: https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/certs
