apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "neptune.fullname" . }}
  labels:
    app: {{ template "neptune.name" . }}
    chart: {{ template "neptune.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    app:
      oauth2:
        base-url: {{ .Values.app.oauth2.baseUrl }}
        realm: {{ .Values.app.oauth2.realm }}
    ceres:
      url: {{ .Values.ceres.url | default (printf "http://%s-ceres.%s.svc.cluster.local" .Release.Name .Release.Namespace)}}
      model: {{ .Values.ceres.model }}
    spring:
      datasource:
        url: "jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}:5432/{{ .Values.postgresql.postgresDatabase }}"
        username: "{{ .Values.postgresql.postgresUser }}"
        password: "{{ .Values.postgresql.postgresPassword }}"


