apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "neptune.fullname" . }}
  labels:
    app: {{ template "neptune.name" . }}
    chart: {{ template "neptune.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    app:
      oauth2:
        base-url: {{ .Values.app.oauth2.baseUrl }}
        realm: {{ .Values.app.oauth2.realm }}
      metadata:
        base-url: {{ .Values.app.metadata.baseUrl }}
    ceres:
      url: {{ .Values.ceres.url | default (printf "http://%s-ceres.%s.svc.cluster.local" .Release.Name .Release.Namespace)}}
    titan:
      url: {{ .Values.titan.url | default (printf "http://%s-titan.%s.svc.cluster.local" .Release.Name .Release.Namespace)}}
    spring:
      zipkin:
        enabled: {{ .Values.tracing.enabled }}
        base-url: {{ .Values.tracing.baseUrl }}
      datasource:
        url: "jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}:5432/{{ .Values.postgresql.postgresDatabase }}"
        username: "{{ .Values.postgresql.postgresUser }}"
        password: "{{ .Values.postgresql.postgresPassword }}"
      rabbitmq:
        host: {{ .Values.rabbitmq.hostname }}
        username: {{ .Values.rabbitmq.username | default (printf "%s-neptune" .Release.Name) }}
        password: {{ .Values.rabbitmq.password }}
        virtualHost: {{ .Values.rabbitmq.vhost | default .Release.Name }}

