app:
  oauth2:
    base-url: http://192.168.99.100:30881
    realm: curie

spring:
  datasource:
    url: "jdbc:h2:mem:neptune"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

ceres:
  url: "http://localhost:8001"

titan:
  url: "http://localhost:3000"

server:
  port: 8082
