spring:
  datasource:
    url: "jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
  jpa:
    hibernate:
      ddl-auto: update
ceres:
  url: "http://localhost:8001"
  endpoint: "/model/mymodel/statements"
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
      prefer-token-info: false
      jwk:
        key-set-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/certs
