# Some basic oAuth parameters that can easily be used in other places
app:
  oauth2:
    base-url: http://localhost:9080
    realm: keycloak
  metadata:
    base-url: http://fairspace.com

# Configuration for sql database which stores predicates and labels
spring:
  application:
    name: Neptune
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://jaeger-collector.jaeger:9411/
  datasource:
    url: "jdbc:postgresql://demo-postgresql:5432/postgres"
    username: "postgres"
    password: "test123"
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mvc:
    static-path-pattern: /static/**
  resources:
    cache:
      period: 604800s
      cachecontrol:
        max-age: 604800s
        cache-public: true

# Pointer to the Ceres service
ceres:
  url: "http://localhost:8001"

titan:
  url: "http://localhost:8002"

# Security configuration
security:
  oidc:
    jwk-key-set-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/certs
  urls:
    permitAll:
    - /actuator/health
    needsAuthentication:
    - /*