app:
  mail:
    from: info@fairspace.com
  rabbitmq:
    enabled: true
    topology:
      collections:
        exchange: "collections"
        queues:
          addPermission: "collections.callisto.add_permission"

spring:
  application:
    name: Callisto
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://jaeger-collector.jaeger:9411/

