#spring:
#  datasource:
#    url: "jdbc:h2:mem:"

spring:
  datasource:
    url: "jdbc:postgresql://192.168.99.100:30187/postgres"
    username: "postgres"
    password: "test123"
  jpa:
    hibernate:
      ddl-auto: update
    #generate-ddl: true


ceres:
  url: "http://localhost:8001"
  endpoint: "/model/mymodel/statements"
