apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ceres.fullname" . }}
  labels:
    app: {{ template "ceres.name" . }}
    chart: {{ template "ceres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    server.port: {{ .Values.service.internalPort }}

    # OAuth2 base configuration
    app:
      oauth2:
        base-url: {{ .Values.app.oauth2.baseUrl }}
        realm: {{ .Values.app.oauth2.realm }}

    # Tracing configuration
    spring:
      sleuth:
        sampler:
          probability: {{ .Values.app.tracing.samplingRate }}
      zipkin:
        base-url: {{ .Values.app.tracing.zipkinUrl }}

    # Where to store the dataset
    jena:
      dataset:
        path: {{ .Values.persistence.mountPath }}
