apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ceres.fullname" . }}
  labels:
    app: {{ template "ceres.name" . }}
    chart: {{ template "ceres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ceres.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ceres.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
          env:
          - name: CERES_DATA_DIR
            value: "{{ .Values.persistence.mountPath }}"
          - name: CERES_AUTH_ENABLED
            value: "{{ .Values.ceres.auth.enabled }}"
          - name: CERES_AUTH_ISSUER
            value: "{{ .Values.ceres.auth.jwt.issuer }}"
          - name: CERES_AUTH_REALM
            value: "{{ .Values.ceres.auth.jwt.realm }}"
          - name: CERES_AUTH_AUDIENCE
            value: "{{ .Values.ceres.auth.jwt.audience }}"
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
