apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titan.fullname" . }}
  labels:
    app: {{ template "titan.name" . }}
    chart: {{ template "titan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: {}
