apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "titan.fullname" . }}
  labels:
    app: {{ template "titan.name" . }}
    chart: {{ template "titan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge | default "0%" }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable | default "100%" }}
  selector:
    matchLabels:
      app: {{ template "titan.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "titan.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
      {{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
              - name: CONFIG_FILE
                value: "/config/config.json"
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.rootPath }}
            subPath: {{ .Values.persistence.subPath }}
          - name: config-volume
            mountPath: /config
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
              - name: Probe
                value: Liveness
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
              - name: Probe
                value: Readiness
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "titan.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: config-volume
        configMap:
        name: {{ template "titan.fullname" . }}-config
