apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "titan.fullname" . }}
  labels:
    app: {{ template "titan.name" . }}
    chart: {{ template "titan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge | default "0%" }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable | default "100%" }}
  selector:
    matchLabels:
      app: {{ template "titan.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "titan.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
              - name: AUTH_ENABLED
                value: "{{ .Values.auth.enabled }}"
              - name: JWKS_URL
                value: "{{ .Values.auth.jwksUrl }}"
              - name: TRACING_ENABLED
                value: "{{ .Values.tracing.enabled }}"
              - name: ZIPKIN_URL
                value: "{{ .Values.tracing.zipkinUrl }}"
              - name: ZIPKIN_SAMPLING_RATE
                value: "{{ .Values.tracing.samplingRate }}"
              - name: PERMISSIONS_URL
                value: "{{ .Values.permissions.collectionPermissionsUrl }}"
          volumeMounts:
          - name: data
            mountPath: /data
            subPath: {{ .Values.persistence.subPath }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
              - name: Probe
                value: Liveness
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
              - name: Probe
                value: Readiness
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "titan.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
