apiVersion: v1
kind: Service
metadata:
  name: {{ template "neptune.fullname" . }}
  labels:
    app: neptune
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.neptune.service.type }}
  ports:
    - port: {{ .Values.neptune.service.externalPort }}
      targetPort: {{ .Values.neptune.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: neptune
    release: {{ .Release.Name }}
