app:
  oauth2:
    base-url: http://localhost:9080
    realm: keycloak
    logout-url: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/logout?redirect_uri=%s
    redirect-after-logout-url: https://fairspace.com
    required-authority: user-workspace

  # Specify urls for security configuration. There are
  urls:
    permitAll:
    - /actuator/health
    - /error
    - /manifest.json
    needsAuthentication:
    - /account/name
    needsAuthorization:
    - /account/authorizations
    - /storage
    - /api/metadata

security:
  oauth2:
    client:
      clientId: web_app
      clientSecret: web_app
      user-authorization-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/auth
      access-token-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/token
      authentication-scheme: header
      scope: openid
    resource:
      jwk:
        key-set-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/certs
      user-info-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/userinfo
      prefer-token-info: false

zuul:
  routes:
    storage:
      path: /api/storage/**
      url: http://titan/
      strip-prefix: false
    metadata:
      path: /api/metadata/**
      url: http://ceres/
    collections:
      path: /api/collections/**
      url: http://neptune/
    ui:
      path: /**
      url: http://mercury/
  ignored-patterns:
  - /actuator/**
  - /account/**
  - /login
  - /logout
  add-host-header: true
  ignored-headers:
    - Access-Control-Allow-Credentials
    - Access-Control-Allow-Origin
    - Pragma
    - X-Frame-Options
    - X-Content-Type-Options
    - X-XSS-Protection
