app:
  forceHttps: false
  oauth2:
    base-url: http://keycloak.hyperspace.test.local:31303
    realm: curie
    required-authority: user-fashionable-bison

security:
  oauth2:
    client:
      clientId: fashionable-bison-pluto
      clientSecret: b6a9f4bd-f8b8-4bb5-9223-4040ea05b5f2

zuul:
  routes:
    storage:
      url: http://192.168.99.100:31098/
    ui:
      url: http://192.168.99.100:30721/