pluto:
  oauth2:
    base-url: http://192.168.99.100:31303
    realm: curie
    required-authority: user-ws1

security:
  oauth2:
    client:
      clientId: ws1-pluto
      clientSecret: d51ddd79-f3e0-43ef-8113-997a49164899

