pluto:
  oauth2:
    base-url: http://localhost:9080
    realm: keycloak
    logout-url: ${pluto.oauth2.base-url}/auth/realms/${pluto.oauth2.realm}/protocol/openid-connect/logout?redirect_uri=%s
    redirect-after-logout-url: https://www.google.com

security:
  oauth2:
    client:
      clientId: web_app
      clientSecret: web_app
      user-authorization-uri: ${pluto.oauth2.base-url}/auth/realms/${pluto.oauth2.realm}/protocol/openid-connect/auth
      access-token-uri: ${pluto.oauth2.base-url}/auth/realms/${pluto.oauth2.realm}/protocol/openid-connect/token
      authentication-scheme: header
    resource:
      user-info-uri: ${pluto.oauth2.base-url}/auth/realms/${pluto.oauth2.realm}/protocol/openid-connect/userinfo
      prefer-token-info: false

zuul:
  routes:
    ui:
      path: /ui/**
      url: http://localhost:3000/
    workspaces:
      path: /workspaces/**
      url: http://localhost:8088/
      strip-prefix: false