language: ruby

os:
- linux

env:
  global:
  - RELEASE_BRANCH="master"
  - SNAPSHOT_BRANCH="dev"
  - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
  - GITHUB_USERNAME="fairspace-ci"
  # GITHUB_PASSWORD = ...
  - secure: "X+RjIN9Il2D6ruTtP+QJv38yIIg2CCVo0TH/pgwuRQKfud6E2iORXJTgh8bfLZrk4/iK5vCPKLkAUnVrD/IrXwvCQZuicxoVpNPe3YnlfrjJ6Y6qGhM7l4j2hL08DURCrbJ6qaRFUoVtgJxTEhW+kx03iQtV0WkwUakQ3p6qcj3WYfeL6vAworj6A2cPTpels4dz5PeFkD+uZ0OyKwrEG2BDRtgZT+IV83J19visltS47xuCytcBH+n11+T3O/0CdVwi6F7jh7AofagiBdYjAvH9TiReJ+thse6m+aG7XyTCKyBhTo5Kgm7XoWcmYRqbD8Q546OzW60NaNFHh+cdKbUBP45dZ2/0SHkgJsifgZpIccRaawrRGTdzyZXPLyyLRjWJwzXxvZD3i3VrLmijqbC+sVePGs7Z/jp/qL5EGPi/180aB2YvQyZecZ8KKHuQu0g2iLs912LwrYGpsuAhhT1l6M7YJzE1KswVE7b/n36vzrsk3805Gl2tdjCTPdMxVVlXs9z+0yPxPUy6hIYFK92JAXggkOsq5SP9/KgyQL3OQ8S7LuXp0Mm3dX2RM+ReOM1z3vBl6aI5ldUaXfH8CFOcGgBK4CqnN9UZEhNCbAGXHRI+wg5RZzVVTlbhuV5ICbTTuk/rv7FZ75mDgwDZN8bAe3QKwkEdhbCS8eqqMHg="
  - NEXUS_USERNAME="travis-fairspace"
  # NEXUS_PASSWORD = ...
  - secure: "U2jl94URbr+yJ4Aj1ePkHyV+pZfbq/DJOHzgbQ6tZX3Uqckc6OE0JJ7O/fL3eZsbtrAh4uiH9nRdd6ESlMEMb2bzmwZCZifLsISmv8kIYbGi39tP8qIvky2VtA8fcO2RKgsCnNQ712R5Athfxkf59OZEMqO9bFYbRFAMhGy4v+MMLFi9dDoutz6ui/uS9sCNvTCPVrotGEiAGiyxu0pRHq05/q11J9YblCcsiU4a6Ym+/yoLcuQaa8+x59xmWbiiCoSblIUVtVtSLZcuycQuPnuLHnoJxKvEzjTxGe6w0QgHh5gH6ZuvxuiMWZcI9Hc/B0muie7SPeg4+TrdtBzoc1PjjQr80LoGq9E0Pi2uV/4JZuwpIB04rHsVoh6imOPKotyDUVVYz07vlnZu5i4YFIoclVcceilz4G/Glk2gAJ6RskU2PDE+p1dlC6k9UGXTOpU120qXZCu8nv6JiArucnfWG3ZptWAkCwXPghsDledPgGfYC0GEYXfqE97msjRVUXrftRNsiLqmtc/0GGbOrabUTG+CKPguZ6riFcdVeqRDJwqO/MHsEFXA3U96bKN6EvqrA7CMw/xUTB0p/pwq2dNFtxjEJIIuUPdIH2EmVcCWWvTWNqNtSKucVzTOedOYIGCWrOHq93T8lhJBB4lg05VlWaurYTPu/kEhDsbe6XY="

before_install:
- git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
- source ./ci/setup_env.sh

jobs:
  include:
  - stage: Build
    name: Build artifact
    script:
    - ./ci/gradle/build.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/gradle/publish.sh; fi'
  - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
    stage: Versioning
    name: Set tag and update version
    script:
    - "./ci/versioning/add_tag_to_git.sh"
    - "./ci/versioning/set_next_version.sh"

notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      secure: "bXnVAB6ZU3rVgh/dCU5wdzzjRMaNIAPgBIC+dRahq1tRsQazuFfFPchj+VUnqQ7hgm4a7+OlVb/e82vKQ941nFkM2eo61eiJx5EX4VMITl8Hh9TwRfAPsT0iB9ay9grUG1XREDbprAcnjvWMsyq9w5ye348PGQF5RLYvtXGm1o4JbVVrfn9afM95VHwRVLw0YwdwBRV0Z8A8Ejyy+9nwBuM3gjTCI8DoOS985rETcp/hN6EYiR7IJExXefWKm09gZplQfgSo2QG2yqfTU6EYdbWIY48eaLKUFIBmP8LX0HyxbpuxWhgPt9RWMgLmE/rbWr2uRgn6nWW/rZOMkLv2CD03XTN8NW2jnUEL/FL89EvOeY6vsPS1qCdhwxPR+xEJQU43tssbFCCWRBlV91WwcaTcNnseUpw10ldEMCQl1GVjvXd9yjzsX2NsL1h1Kxz5HY7ByTvBlrOdVZABQjazcKoGvoWrfXOse24vXHl7jCeMolg940BPzBJh7ugX3ejNEUlcAivwXneHIsDEYazTDpF4sZwrg7G9SpqiSC0Zbvc/9WbXr6UkFVAh5L60yUgt+LBRPgbPKXs1mjOhs9qgsnAMUsGUG2O4/FyrshFWA80/JZnIpsmbZXHB5z1m9OloJPnK97lUtxhlgpYzHR8PUarq3gX4HYDTTcFzu1HqgXA="
    template:
    - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} -
      <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true
