
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: preview.test.fairdev.app
    exposer: Ingress
    http: false
    tlsacme: true

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 400m
      memory: 768Mi