apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pluto
  labels:
    app: pluto
    {{- include "fairspace.labels" . | nindent 4 }}
data:
  application.yaml: |-
    pluto:
      domains:
        - https://{{ .Values.fairspace.ingress.domain }}
{{ if .Values.pluto.externalDomains }}{{ toYaml .Values.pluto.externalDomains | indent 8 }}{{ end }}
      oauth2:
        base-url: {{ .Values.external.keycloak.baseUrl }}
        realm: {{ .Values.external.keycloak.realm }}
      storages:
{{ toYaml .Values.fairspace.storages | indent 8 }}

    management:
      endpoint:
        health:
          probes:
            enabled: true

    logging:
      level:
        root: {{ .Values.pluto.logLevel }}

    server:
      error:
        whitelabel:
          enabled: false
      max-http-header-size: 65535

    security:
      oidc:
        redirect-after-logout-url: https://{{ .Values.fairspace.ingress.domain }}/login
        clientId: {{ .Values.external.keycloak.clientId }}
        clientSecret: {{ .Values.external.keycloak.clientSecret }}

    spring:
      zipkin:
        enabled: {{ .Values.tracing.enabled }}
        base-url: {{ .Values.tracing.baseUrl }}
      servlet:
        multipart:
          max-file-size: {{ .Values.pluto.maxFileSize }}
          max-request-size: {{ .Values.pluto.maxRequestSize }}

    zuul:
      retryable: false
      host:
        connect-timeout-millis: {{ .Values.pluto.connectTimeoutMillis }}
        socket-timeout-millis: {{ .Values.pluto.socketTimeoutMillis }}
      routes:
{{ if .Values.pluto.backends.storageRoutes }}
{{ toYaml .Values.pluto.backends.storageRoutes | indent 8 }}
{{ end }}
        saturn:
          path: /api/**
          url: {{ .Values.pluto.backends.saturn | default "http://localhost:8090"}}
          strip-prefix: false
      add-proxy-headers: false
