kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-saturn-audit
  labels:
    app: saturn
    {{- include "fairspace.labels" . | nindent 4 }}
{{- if .Values.saturn.persistence.audit.annotations }}
  annotations:
{{ toYaml .Values.saturn.persistence.audit.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.saturn.persistence.audit.size | quote }}
{{- if .Values.saturn.persistence.audit.storageClass }}
  {{- if (eq "-" .Values.saturn.persistence.audit.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.saturn.persistence.audit.storageClass | quote }}
  {{- end }}
{{- end }}
