# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.cbiotest.fairway.app
  locationOverrides:
    keycloak: https://cbioportal-fairspace.thehyve.net:8443
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: cbio
    clientId: workspace-test-pluto
    clientSecret: baf559f1-1926-44c2-95c9-b635639918b0

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.cbiotest.fairway.app
    tls:
      certificate:
        dns01Provider: azuredns-cbiotest
  configurationScripts:
    keycloak:
      enabled: false

# Specific settings for Pluto
pluto:
  image:
    image: fairspace.azurecr.io/fairspace/pluto
    pullPolicy: Always

# Specific settings for Mercury
mercury:
  image:
    image: fairspace.azurecr.io/fairspace/mercury
    pullPolicy: Always

# Specific settings for Saturn
saturn:
  image:
    image: fairspace.azurecr.io/fairspace/saturn
    pullPolicy: Always
