# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.ci.fairway.app
  locationOverrides:
    rabbitmqhostname: hyperspace-ci-rabbitmq.hyperspace-ci.svc.cluster.local
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
  rabbitmq:
    username: rabbitmq
    password: "X6SXtXV3Jzg4gyVR"

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.ci.fairway.app
    tls:
      certificate:
        dns01Provider: azuredns-ci
  enableExperimentalFeatures: true

pluto:
  image:
    pullPolicy: Always
  rabbitmq:
    password: "PaF6ZMbDZmgrztJY"

titan:
  image:
    pullPolicy: Always
  rabbitmq:
    password: "L3bE8yGJp7um2PVk"
  persistence:
    size: 20Gi

# Specific settings for Ceres subchart
ceres:
  image:
    pullPolicy: Always
  rabbitmq:
    password: "hx6SQUBe99EBr8dM"

# Specific settings for Neptune subchart
neptune:
  image:
    pullPolicy: Always
  rabbitmq:
    password: "4uXa4BFkHTuNxFAF"

# Specific settings for Mercury subchart
mercury:
  image:
    pullPolicy: Always

# Specific settings for Callisto subchart
callisto:
  rabbitmq:
    password: "6hfdJUr7RW6LTFgB"

  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIAISXHGXUIMMU75YVA
    password: Avjpey3XBSvnlPfWGTS2qEjiJykvbDJtj6zWW3fCZILl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# Specific settings for JupyterHub subchart
jupyterhub:
  rbac:
    enabled: false
  auth:
      custom:
          config:
              client_id: workspace-ci-pluto
              client_secret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
              openid_url: https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/
              session_url: https://workspace.ci.fairway.app/account/tokens
  singleuser:
    image:
      tag: 0.5.3-SNAPSHOT-simple
    extraEnv:
      WORKSPACE_URL: https://storage.workspace.ci.fairway.app
  hub:
      extraEnv:
          JUPYTERHUB_CRYPT_KEY: 61efcb6349da848c361e13c0edfac1486d636ef89a2b7cbba610e83d8a332026
  proxy:
      secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"
