# External dependencies for running the fairspace
external:
  keycloak:
    baseUrl: https://keycloak.demo.fairway.app
    username: keycloak
    password: keycloak-demo-123
    realm: demo
    clientId: fairspace-demo-private
    clientSecret: db67da94-fa31-47cd-8c42-0ed295790841
    serviceAccount:
      password: fairspace123
  elasticsearch:
    enabled: true
    transport:
      host: fairspace-demo-elasticsearch-discovery.fairspace-demo.svc.cluster.local
    rest:
      host: fairspace-demo-elasticsearch-client.fairspace-demo.svc.cluster.local

# Settings for the fairspace
fairspace:
  name: "Demo Fairspace"
  description: "Demo Fairspace"
  ingress:
    domain: fairspace.demo.fairway.app
  enableExperimentalFeatures: true
  configurationScripts:
    keycloak:
      pullPolicy: IfNotPresent

services:
  jupyterhub: https://jupyter.fairspace.demo.fairway.app


# Specific settings for Saturn subchart
saturn:
  persistence:
    files:
      size: 60Gi
      storageClass: expandable
    database:
      size: 60Gi
      storageClass: expandable
  resources:
    limits:
      cpu: 1
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 512Mi
  image:
    pullPolicy: Always
  customStorageClass:
    create: true
    name: expandable
    type: pd-standard
    provisioner: kubernetes.io/gce-pd
    allowVolumeExpansion: true

# Specific settings for Mercury subchart
mercury:
  image:
    pullPolicy: Always
# Specific settings for Mercury subchart
docs:
  image:
    pullPolicy: Always
