# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.gkeci.fairway.app
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: gkeci
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.gkeci.fairway.app
    tls:
      certificate:
        dns01Provider: gke
  enableExperimentalFeatures: true
  configurationScripts:
    keycloak:
      enabled: true
      image: eu.gcr.io/fairspace-207108/keycloak-configuration:0.1.1
      pullPolicy: IfNotPresent

pluto:
  image:
    image: eu.gcr.io/fairspace-207108/pluto
    pullPolicy: Always

# Specific settings for Saturn subchart
saturn:
  image:
    image: eu.gcr.io/fairspace-207108/saturn
    pullPolicy: Always

# Specific settings for Mercury subchart
mercury:
  image:
    image: eu.gcr.io/fairspace-207108/mercury
    pullPolicy: Always

# Specific settings for JupyterHub subchart
jupyterhub:
  rbac:
    enabled: true
  auth:
      custom:
          config:
              client_id: workspace-gkeci-pluto
              client_secret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
              openid_url: https://keycloak.hyperspace.gkeci.fairway.app/auth/realms/gkeci/protocol/openid-connect/
              session_url: https://workspace.gkeci.fairway.app/account/tokens
  singleuser:
    image:
      name: eu.gcr.io/fairspace-207108/jupyterhub-singleuser
      tag: 0.5.4-SNAPSHOT-simple
    extraEnv:
      WORKSPACE_URL: https://storage.workspace.gkeci.fairway.app
  hub:
    image:
      name: eu.gcr.io/fairspace-207108/jupyterhub-hub
    extraEnv:
      JUPYTERHUB_CRYPT_KEY: 61efcb6349da848c361e13c0edfac1486d636ef89a2b7cbba610e83d8a332026
  proxy:
      secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"
