# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.test.fairway.app
  locationOverrides:
    keycloak: https://cbioportal-fairspace.thehyve.net:8443
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: cbio
    clientSecret: baf559f1-1926-44c2-95c9-b635639918b0

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.test.fairway.app
    tls:
      certificate:
        dns01Provider: azuredns-test
  configurationScripts:
    keycloak:
      enabled: false

pluto:
  image:
    pullPolicy: Always

# Specific settings for Saturn subchart
saturn:

# Specific settings for Mercury subchart
mercury:
  image:
    pullPolicy: Always


# Specific settings for JupyterHub subchart
jupyterhub:
  rbac:
    enabled: false
  auth:
      custom:
          config:
              client_id: workspace-test-pluto
              client_secret: baf559f1-1926-44c2-95c9-b635639918b0
              openid_url: https://cbioportal-fairspace.thehyve.net:8443/auth/realms/cbio/protocol/openid-connect/
              session_url: https://workspace.test.fairway.app/account/tokens
  singleuser:
    image:
      tag: 0.5.3-SNAPSHOT-simple
    extraEnv:
      WORKSPACE_URL: https://workspace.test.fairway.app
  hub:
      extraEnv:
          JUPYTERHUB_CRYPT_KEY: 347947239749dbea93432379223064342aa5754843349978ef78978954397836
  proxy:
      secretToken: "505043750470347507534554340b45754037a4840482308908e985805208093a"
