# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.test.fairspace.app
  keycloak:
    username: keycloak
    password: yJH7qVjAQ469MVNBR9L5
    realm: test
    clientSecret: db67da94-fa31-47cd-8c42-0ed295790841

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.test.fairspace.app
    tls:
      certificate:
        dns01Provider: gke

# Specific settings for Pluto subchart
pluto:
  keycloak:
    baseUrl: https://keycloak.hyperspace.test.fairspace.app
    realm: test
  tracing:
    enabled: false

# Specific settings for Saturn subchart
saturn: {}

mercury: {}
