# External dependencies for running the fairspace
external:
  keycloak:
    baseUrl: https://keycloak.ci.fairway.app
    realm: ci
    clientId: fairspace-ci-private
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
    serviceAccount:
      password: fairspace123
  elasticsearch:
    enabled: false

# Settings for fairspace
fairspace:
  name: "Test Fairspace"
  description: "Test Fairspace"
  ingress:
    domain: fairspace.test.fairway.app
  features:
  services:
    JupyterHub: https://jupyter.fairspace.ci.fairway.app/user/${username}/lab
  storages:

# Specific settings for Saturn subchart
saturn:
  persistence:
    files:
      size: 60Gi
      storageClass: expandable
    database:
      size: 60Gi
      storageClass: expandable
  resources:
    limits:
      cpu: 1
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 512Mi
  customStorageClass:
      create: true
      name: expandable
      type: pd-standard
      provisioner: kubernetes.io/gce-pd
      allowVolumeExpansion: true
