kind: Secret
apiVersion: v1
metadata:
  name: {{ template "workspace.fullname" . }}-keycloak-creds-teardown
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  password: {{ .Values.hyperspace.keycloak.password | default "" | b64enc | quote }}
