# Default values for neptune.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: neptune
  tag: 0.4
  pullPolicy: Never

service:
  name: neptune
  type: NodePort
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 400m
    memory: 768Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

workspace:
  name:

keycloak:
  baseUrl:
  client:
    id:
    secret:
  realm:
  redirectAfterLogoutUrl: https://fairspace.com
  requiredAuthority:

ceres:
  url:
  edpoint:

postgresUser: postgres
postgresPassword: test123
postgresDatabase: postgres

spring:
  datasource:
    url: 
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

