apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titan.fullname" . }}
  labels:
    app: titan
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |-
    {
      "rootPath": "{{ .Values.titan.persistence.rootPath }}",
      "basePath":"/api/storage/webdav",
      "auth": {
        "enabled": {{ .Values.titan.auth.enabled }}
      },
      "tracing": {
        "enabled": {{ .Values.tracing.enabled }},
        "zipkinUrl": "{{ .Values.tracing.zipkinUrl }}",
        "samplingRate": {{ .Values.tracing.samplingRate }}
      },
      "rabbitmq": {
        "host": "{{ .Values.titan.rabbitmq.hostname }}",
        "vhost": "{{ .Values.titan.rabbitmq.vhost | default .Release.Name }}",
        "user": "{{ .Values.titan.rabbitmq.username | default (printf "%s-titan" .Release.Name) }}",
        "pass": "{{ .Values.titan.rabbitmq.password }}",
        "exchange": "{{ .Values.titan.rabbitmq.exchange }}"
      },
      "urls":{
        "collections": "{{ .Values.titan.collections.collectionUrl | default (printf "http://%s-neptune.%s.svc.cluster.local/?location=%%s" .Release.Name .Release.Namespace)}}"
      }
    }

