apiVersion: v1
kind: Service
metadata:
  name: {{ template "titan.fullname" . }}
  labels:
    app: titan
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.titan.service.type }}
  ports:
  - port: {{ .Values.titan.service.externalPort }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: titan
    release: {{ .Release.Name }}
