# Where to store the dataset
jena:
  dataset:
    path: /tmp/data

app:
  oauth2:
    base-url: http://localhost:5100
    realm: minikube

# Tracing configuration
spring:
  zipkin:
    enabled: false
  rabbitmq:
    host: localhost
    username: guest
    password: guest

server:
  port: 5120
