# OAuth2 base configuration
app:
  oauth2:
    base-url: http://localhost:9080
    realm: keycloak
  metadata:
    base-url: http://fairspace.com/
    infix: iri/files
  rabbitmq:
    enabled: true
    topology:
      storage:
        exchange: "storage"
        queues:
          create: "storage.ceres.create"
          move:   "storage.ceres.move"
          copy:   "storage.ceres.copy"
          delete: "storage.ceres.delete"

# Security configuration
security:
  oidc:
    jwk-key-set-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/certs
  urls:
    permitAll:
    - /actuator/health
    needsAuthentication:
    - /*

# Where to store the dataset
jena:
  dataset:
    path: data

# Tracing configuration
spring:
  application:
    name: Ceres
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    base-url: http://jaeger-collector.jaeger:9411/

server:
  error:
    whitelabel:
      enabled: false