# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.ci.test.fairdev.app
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.ci.test.fairdev.app

pluto:
  keycloak:
    baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
    realm: ci
  tracing:
    samplingRate: 1
  services:
    jupyter: https://jupyterhub.workspace.ci.test.fairdev.app

titan:
  auth:
    tokenUrl: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/token
    clientId: workspace-ci-pluto
  tracing:
    samplingRate: 1
  permissions:
    collectionPermissionsUrl: https://workspace.ci.test.fairdev.app/api/collections/permissions?location=%s

# Specific settings for Ceres subchart
ceres:
  app:
    oauth2:
      baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
      realm: ci
    tracing:
      samplingRate: 1

# Specific settings for Neptune subchart
neptune:
  app:
    oauth2:
      baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
      realm: ci
    tracing:
      samplingRate: 1
    metadata:
      baseUrl: https://workspace.ci.test.fairdev.app

# Specific settings for JupyterHub subchart
jupyterhub:
    auth:
        custom:
            config:
                client_id: workspace-ci-pluto
                client_secret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
    singleuser:
        image:
            name: docker-registry.jx.test.fairdev.app/fairspace/jupyterhub-singleuser
            tag: 0.1.27
    hub:
        image:
            name: docker-registry.jx.test.fairdev.app/fairspace/jupyterhub-hub
            tag: 0.1.4
        extraEnv:
            OPENID_CONNECT_URL: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect
            JUPYTERHUB_CRYPT_KEY: 61efcb6349da848c361e13c0edfac1486d636ef89a2b7cbba610e83d8a332026
    proxy:
        secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"
