# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.ci.test.fairdev.app
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.ci.test.fairdev.app

pluto:
  keycloak:
    baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
    realm: ci

titan:
  jwksUrl: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/certs

# Specific settings for Ceres subchart
ceres:
    ceres:
      auth:
        enabled: true
        jwt:
          issuer: https://keycloak.hyperspace.ci.test.fairdev.app
          realm: ci
          audience: 

# Specific settings for Neptune subchart
neptune:
    app:
      oauth2:
        baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
        realm: ci
      metadata:
        baseUrl: https://workspace.ci.test.fairdev.app
