apiVersion: v1
kind: Service
metadata:
  name: {{ template "titan.fullname" . }}
  labels:
    app: {{ template "titan.name" . }}
    chart: {{ template "titan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ template "titan.name" . }}
    release: {{ .Release.Name }}
