apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "mercury.fullname" . }}-server
    labels:
        app: mercury
        chart: {{ template "fairspace.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
data:
    config.yaml: |-
      urls:
        keycloak: {{ .Values.external.keycloak.baseUrl }}
        elasticsearch: {{ template "elasticsearch.baseurl" . }}
        saturn: http://{{ .Release.Name }}-saturn.{{ .Release.Namespace }}.svc.cluster.local
      keycloak:
        realm: {{ .Values.external.keycloak.realm }}
        clientId: {{ .Values.external.keycloak.clientId }}
