apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "saturn.fullname" . }}
  labels:
    app: saturn
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    baseURI: {{ template "workspace.url" . }}/iri/
    port: 8080
    jena:
      baseURI: "http://localhost/iri/"
      datasetPath: "/data/db"
      transactionLogPath: "/data/store/log"
      elasticSearch:
        enabled: false
        settings:
          hostToPortMapping:
            localhost: 9300
          clusterName: "elasticsearch"
          shards: 1
          replicas: 1
          indexName: "fairspace"
    auth:
      authEnabled: true
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: "RS256"
    webDAV:
      blobStorePath: "/data/store/blobs"