apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "saturn.fullname" . }}
  labels:
    app: saturn
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    port: 8080
    jena:
      metadataBaseIRI: http://{{ template "pluto.hostname" . }}/iri/
      vocabularyBaseIRI: http://{{ template "pluto.hostname" . }}/vocabulary/
      datasetPath: "/data/saturn/db"
      transactionLogPath: "/data/saturn/files/log"
      metadataTripleLimit: {{ .Values.saturn.metadataTripleLimit }}
      elasticSearch:
        enabled: {{ .Values.workspace.elasticsearch.enabled }}
        required: false
        settings:
          hostToPortMapping:
            {{ template "workspace.elasticsearch.transporthost" . }}: {{ .Values.workspace.elasticsearch.transportport }}
          clusterName: "elasticsearch"
          shards: 1
          replicas: 1
          indexName: "fairspace"
    users:
      endpoint: https://{{ template "pluto.hostname" . }}/api/v1/workspace/users
      synchronizationInterval: 60
    auth:
      enabled: true
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: "RS256"
      workspaceUserRole: "{{ .Values.workspace.keycloak.roles.user | default (printf "user-%s" (include "workspace.name" .)) }}"
      dataStewardRole: "{{ .Values.workspace.keycloak.roles.datasteward | default (printf "datasteward-%s" (include "workspace.name" .)) }}"
      sparqlRole: "{{ .Values.workspace.keycloak.roles.sparql | default (printf "sparql-%s" (include "workspace.name" .)) }}"
    webDAV:
      blobStorePath: "/data/saturn/files/blobs"
    mail:
{{ toYaml .Values.saturn.mail | indent 6 }}

