apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "saturn.fullname" . }}
  labels:
    app: saturn
    chart: {{ template "workspace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    port: 8080
    publicUrl: {{ template "workspace.url" . }}
    jena:
      metadataBaseIRI: http://{{ template "pluto.hostname" . }}/iri/
      vocabularyBaseIRI: http://{{ template "pluto.hostname" . }}/vocabulary/
      datasetPath: "/data/saturn/db"
      transactionLogPath: "/data/saturn/files/log"
      maxTriplesToReturn: {{ .Values.saturn.maxTriplesToReturn }}
      elasticSearch:
        enabled: {{ .Values.hyperspace.elasticsearch.enabled }}
        required: true
        settings:
          hostToPortMapping:
            {{ .Values.hyperspace.elasticsearch.transport.host }}: {{ .Values.hyperspace.elasticsearch.transport.port }}
          clusterName: "elasticsearch"
          shards: 1
          replicas: 1
          indexName: "{{ .Values.hyperspace.elasticsearch.indexName }}"
    auth:
      enabled: true
      jwksUrl: {{ template "keycloak.baseUrl" . }}/auth/realms/{{ .Values.hyperspace.keycloak.realm }}/protocol/openid-connect/certs
      jwtAlgorithm: "RS256"
      workspaceUserRole: "{{ template "workspace.roles.user" . }}"
      dataStewardRole: "{{ template "workspace.roles.datasteward" . }}"
      sparqlRole: "{{ template "workspace.roles.sparql" . }}"
      userUrlTemplate: "{{ template "keycloak.baseUrl" . }}/auth/admin/realms/{{ .Values.hyperspace.keycloak.realm }}/users/%s"
    webDAV:
      blobStorePath: "/data/saturn/files/blobs"
    workspace:
      id: "{{ .Release.Name }}",
      name: "{{ .Values.workspace.name }}",
      version: "{{ .Chart.Version }}"
    rabbitMQ:
      enabled: {{ .Values.rabbitmq.enabled }}
      required: {{ .Values.rabbitmq.required }}
      host: {{ .Values.hyperspace.rabbitmq.host }}
      username: {{ .Values.rabbitmq.username }}
      password: {{ .Values.rabbitmq.password }}
    mail:
{{ toYaml .Values.saturn.mail | indent 6 }}

