{{- if (or (eq "expandable" .Values.saturn.persistence.database.storageClass) (eq "expandable" .Values.saturn.persistence.files.storageClass)) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: expandable
parameters:
    type: pd-standard
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Delete
{{- end }}