{{- $global := . }}
{{- range .Values.saturn.names }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $global.Release.Name }}-saturn-{{.}}
  labels:
    app: saturn
    chart: {{- printf "%s-%s" $global.Chart.Name $global.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
spec:
  type: {{ $global.Values.saturn.service.type }}
  ports:
    - port: {{ $global.Values.saturn.service.externalPort }}
      targetPort: {{ $global.Values.saturn.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: saturn
    release: {{ $global.Release.Name }}
{{- end}}