version: '3'
services:
  keycloak:
    image: jboss/keycloak:4.6.0.Final
    volumes:
    - ".:/pr"
    networks:
    - e2e-testing
    environment:
      KEYCLOAK_USER: "e2e"
      KEYCLOAK_PASSWORD: "e2e"
      KEYCLOAK_IMPORT: "/pr/config/keycloak/realm.json"
    ports:
    - "8080:8080"
  rabbitmq:
    image: rabbitmq:management
    networks:
    - e2e-testing

  pluto:
    image: fairspace.azurecr.io/fairspace/pluto:${VERSION}
    ports:
      - "22000:8080"
    networks:
      - e2e-testing
    volumes:
      - "./config/pluto:/opt/config"
  mercury:
    image: fairspace.azurecr.io/fairspace/mercury:${VERSION}
    networks:
      - e2e-testing
  neptune:
    image: fairspace.azurecr.io/fairspace/neptune:${VERSION}
    networks:
      - e2e-testing
    depends_on:
      - rabbitmq
    volumes:
    - "./config/neptune:/opt/config"
  ceres:
    image: fairspace.azurecr.io/fairspace/ceres:${VERSION}
    networks:
      - e2e-testing
    depends_on:
      - rabbitmq
    volumes:
      - "./config/ceres:/opt/config"
  titan:
    image: fairspace.azurecr.io/fairspace/titan:${VERSION}
    networks:
      - e2e-testing
    depends_on:
      - rabbitmq
    volumes:
      - ".:/pr"
    environment:
      CONFIG_FILE: "/pr/config/titan/config.json"
    entrypoint:
    - /pr/wait-for-it/wait-for-it.sh
    - --timeout=90
    - --strict
    - rabbitmq:5672
    - --
    - npm
    - start

networks:
  e2e-testing:
