apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-saturn
  labels:
    app: saturn
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    port: 8080
    publicUrl: https://{{ .Values.fairspace.ingress.domain }}
    elasticsearchUrl: {{ template "elasticsearch.baseurl" . }}
    jena:
      metadataBaseIRI: http://{{ .Values.fairspace.ingress.domain }}/iri/
      vocabularyBaseIRI: http://{{ .Values.fairspace.ingress.domain }}/vocabulary/
      datasetPath: "/data/saturn/db"
      storeParams:
{{ toYaml .Values.saturn.storeParams | indent 8 }}
      transactionLogPath: "/data/saturn/files/log"
      bulkTransactions: {{ .Values.saturn.bulkTransactions }}
      elasticSearch:
        enabled: {{ .Values.external.elasticsearch.enabled }}
        required: true
        settings:
          hostToPortMapping:
            {{ .Values.external.elasticsearch.transport.host }}: {{ .Values.external.elasticsearch.transport.port }}
          clusterName: "elasticsearch"
          shards: 1
          replicas: 1
    auth:
      authServerUrl: {{ .Values.external.keycloak.baseUrl }}/auth/
      realm: {{ .Values.external.keycloak.realm }}
      clientId: {{ .Values.external.keycloak.clientId }}
      enableBasicAuth: {{ .Values.saturn.auth.enableBasicAuth }}
    webDAV:
      blobStorePath: "/data/saturn/files/blobs"
    services:
      {{ if ( and .Values.services .Values.services.jupyterhub  ) }}"jupyterhub": "{{ .Values.services.jupyterhub }}"{{ end }}
      {{ if ( and .Values.services .Values.services.cbioportal  ) }}"cbioportal": "{{ .Values.services.cbioportal }}"{{ end }}
    mail:
{{ toYaml .Values.saturn.mail | indent 6 }}

