apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-saturn
  labels:
    app: saturn
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    port: 8080
    publicUrl: https://{{ .Values.fairspace.ingress.domain }}
    privateUrl: http://{{ .Release.Name }}-saturn].{{ .Release.Namespace }}.svc.cluster.local
    jena:
      metadataBaseIRI: http://{{ .Values.fairspace.ingress.domain }}/iri/
      vocabularyBaseIRI: http://{{ .Values.fairspace.ingress.domain }}/vocabulary/
      datasetPath: "/data/saturn/db"
      userUrl: 600
      storeParams:
{{ toYaml .Values.saturn.storeParams | indent 8 }}
      transactionLogPath: "/data/saturn/files/log"
      maxTriplesToReturn: {{ .Values.saturn.maxTriplesToReturn }}
      elasticSearch:
        enabled: {{ .Values.external.elasticsearch.enabled }}
        required: true
        settings:
          hostToPortMapping:
            {{ .Values.external.elasticsearch.transport.host }}: {{ .Values.external.elasticsearch.transport.port }}
          clusterName: "elasticsearch"
          shards: 1
          replicas: 1
    auth:
      enabled: true
      fullAccessRole: organisation-admin
      userUrl: {{ .Values.external.keycloak.baseUrl }}/auth/admin/realms/{{ .Values.external.keycloak.realm }}/users/
    webDAV:
      blobStorePath: "/data/saturn/files/blobs"
    mail:
{{ toYaml .Values.saturn.mail | indent 6 }}

