apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.Release.Name }}-saturn
  labels:
    app: saturn
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{.Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: saturn
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: saturn
        release: {{ .Release.Name }}
{{- if .Values.podAnnotations.saturn }}
      annotations:
{{ toYaml .Values.podAnnotations.saturn | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}-saturn
          image: "{{ .Values.saturn.image.image }}:{{ .Values.saturn.image.tag }}"
          imagePullPolicy: {{ .Values.saturn.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-oauth-client"
                  key: clientSecret
          volumeMounts:
            - name: config-volume
              mountPath: /opt/config
            - name: database
              mountPath: /data/saturn/db
            - name: files
              mountPath: /data/saturn/files
          livenessProbe:
            httpGet:
              path:  /api/v1/health/
              port: 8080
            initialDelaySeconds: {{ .Values.saturn.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.saturn.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.saturn.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.saturn.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path:  /api/v1/health/
              port: 8080
            periodSeconds: {{ .Values.saturn.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.saturn.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.saturn.readinessProbe.timeoutSeconds }}
          resources:
{{ toYaml .resources | indent 12 }}
    {{- with .Values.saturn.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-saturn
      - name: database
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-saturn-database
      - name: files
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-saturn-files

