kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-saturn-files
  labels:
    app: saturn
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.saturn.persistence.files.annotations }}
  annotations:
{{ toYaml .Values.saturn.persistence.files.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.saturn.persistence.files.size | quote }}
{{- if .Values.saturn.persistence.files.storageClass }}
  {{- if (eq "-" .Values.saturn.persistence.files.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.saturn.persistence.files.storageClass | quote }}
  {{- end }}
{{- end }}
