language: java
jdk:
- oraclejdk8
os:
- linux
env:
  global:
  - APPNAME="neptune"
  - ORG="fairspace"
  - ARTIFACT_BUILD_FILE="build.gradle"
  - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
  - RELEASE_BRANCH="master"
  - SNAPSHOT_BRANCH="dev"
  - DOCKER_USERNAME="fairspace"
  - GITHUB_USERNAME="fairspace-ci"
  - HELM_VERSION="2.11.0"
  # DOCKER_PASSWORD = ...
  - secure: "RTwxV0W5ZR22+DXlziPn43hKEvs0hIE3jyOVtrAOylxjy8oxAPJzAadUOuttxBQqIm9+l9prxs6vMyvJJiv+fLkyY65K9MCwMVjKZHZFL2ne+xE/Z/p+EglcX/mQKW7OHX8J/YzS6whzyC/iKHR/MPmhxJnrsWW2mmExHwI9QdSy2KLhQRlxYI7yiX1s2rT0ue3qbRJnTkhYZOd2wbYyAWYOSFdXFuyMAek9f2jzDxUZtxCysnBmWYND7a4QgPnf9lb3yOvF31mUaJa+azrFTThVpbB7bAsTjCiV4tbw7J1LTtzCVkgGWy9eOBglTeWJU4zuszgwkuhVrV2s4hvpMIJxw+jSvLqACQ5EOg0IDhS7EwwZ9nvWahKNx8QD4IsdaeexbKquB2139yEs+akRJzmPjXyZNPD3KTQqdH4zKpLDf3dboBbKFoQDmQsGmUgBe2SLNsUSQ3p5l3+YFsjbbsrevls4t0SR5FCUoOQWP1v7qpGeEOdiNA1VqSIxUoT4IbzphTCmAwQFFsKHhDytkf8OiTkXxp0veSTNXlQ7yqlobfLPKKCwjyN1+FzjcE0F5VTOw6gduso58PJnQrEoUN8Pom+J/7Uiu7RMPXp7PZ4VGY66xrxF/gHPePjnsDhYhlG82l2OwIoaIJ/DdV4PKysWhJW8selAWs/CWriqReA="
  # GITHUB_PASSWORD = ...
  - secure: "Q1CA+IRCvRMxtLFAdIolxDceOPgNl7vHvYhUkKOYbvghBz0ewVyuIDGyUkOrvjCCZR6e3v/qofJ1sQZowo7n+Ko+qhlkGxt8QOhk8YYUHcqDuW7EK6tSyWWbNvcgNoi8sdBt9K5bxW5PskGAx4td5e6SKaSONwC07pPKh0N3yvX8ZpN/KdzXnK+xVlLh3dNIgWgkHftG16XLIoxptUhlSlq4Om7SxU/2LLiltzvKVCcGk5jhpEaXUXMeRIQNXN5rGjqcf4q3BXocI1E0KLn0hNqchjY0a8p7MGdRmulZv79bpGnxAcLaXJzQx2EEuOVgCISfm7pECENXEPeHOzGgi4+mj4AiEMwWTWLhu7DCvaZuwViWoBIke3+8Yu+sEoWefePYWZRRRzSpnaaG+++FDud8HI199bgcZi2HIF1jTxPWwrBQ7L7zXe5WMX2mC36IREx35OYiaym3V91KNw9vvTiLQ60SnfafYDG2tSjgXpsKyqBqIIOKORx+BfFmGP2y/awgLOzctfdKTjNiVmfrsAkklHCudMrK+WbEowsoHNfpAYhkugvSzgYylMY/aZVZcfOxojfZvJVgpYZqUk9OXocAY6/5hkqZ0K/hRplHimBIadRAh7dWZ4F0qRfphfczRAQKA9g+Pp2hPRg/u4cBHG5TKy/lUcb0UCOkl/Yk2Q4="
  # Azure credentials
  - secure: "vAwJDqtrF06C0RuRb54c7h+TZyz5YBjFi+OM2MEMw/eWB+4ZAmgzBo2QBJvUYvJX0T8/zfflHx8aHlZRE7R8QC+mDccNQmBDnabxZBqZOfp9xk6FaNd6EuQ8VDUOMucUkB2oQj3LVGRpXde+HwgoNVbRdQ3F1/M+ZA7QQnDAArGrvHtoEDfv7IkOA+5u8WI8hs0ftLd+bKreB4iTTp7r0SBHGzwqhNK4eYHFiitOQXq9RsXuJ4NaXCOSbSRP7OtNZRdzK0vrYm80yYcylTpz+Y82ROKbb9avJjAswNQJyXDr/E88qtROmc5RJKnPXCRlgnfMxEfYjp1sHxak/fyIJoz/m3OMVOVmgA01oBqxeO2znRovOweBncfS7+F/kOw6zJADh4fuWumM+a9BkJ0P0x9kpTDaQoOsEg8TanjcLYgQCxG9qN5bmnksnv58fIiwOlFso7dY1NFuNPtG1fyn4c+e0WyyStXmeFiou9Pc9PooAfFt8iqUbdtTrYVa84bp0UWhERUUg7gVF/eYhXHO3DupyPyLXogBqIij7iCmXK6SsfOdufF1hdewbSi/BtnNqJ47sRKZY3sGxGhDtq9FO+iIOPX/pqqNCWphP9RJmySuiyyM4ln0IFzXB39BTDs+KAtmbWg+x8agR6zKLVMBXvts4K3P/NnVaqgKy/ZSqgg="
notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      secure: "JCv8jwGjvJH0cVf8zggspoMb5/LiAiDk9fDnNgDpF3cu6+1J1AyU6uc0MYcyPQC2JbmH8psclE2iQEsp2Gv8zVSiqV10VhzmZw/U0or3RP5hgYRGP61yRbQswvDKxr3IJLiJyor4g4ncvCQRyF4+rMWcC/U+w4s0AopAjRpG8E0cOwulz9xGUZgUsQsiVATgLpSk6ZZNuy8uyatNaWN3Lq5hctkB8rg7IqGRdI2MvzhH5+xaZ6KDKOB+iSorbMxL3WtI8RIFEPForDJf7GAc8WeMVIQPHFNMYJCe/amPa9r8oaVcyPiGhVq7YvmMqkDrkVSUrsCez9OKiD71OdIq4hZ0zlHMY3IcpGE/g7ZzNTUiurjmkCF3Sm6J+uuCV+u4GgrxtzivjgxHOwY3wVaoYy2fWF8JbyTvHggTGvP/SsP16B8Fi49ObO/z7PGeiZBXsWcMSgqNbZwLIqePlZFghE806GijKx8GIoKG9x0cbZ1pcoAqTGAfgjFko5ahAWWG2/oYB7QXeOBa0iWYJ0/ythT76OygDCwevEY9TmUgQaOIlFK7XQGPnuiDnk5+CAdoU1lXHdz6mPl68mJ7iJLGXp9wpdPGFdmzNRTe9DVo2DI0fVqNq3u6S3dL0xnoWGF6v83ZRhSssi8I6VVWSqvtL8kKyofntp4ImAdZXoYzWnI="
    template:
    - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} -
      <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true

before_install:
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - source ./ci/setup_env.sh

jobs:
  include:
  - stage: Build
    name: App and Docker image
    services:
    - docker
    cache:
      directories:
      - "$HOME/.gradle"
    script:
    - ./ci/gradle/tag.sh
    - ./ci/gradle/build.sh
    - ./ci/docker/build.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/docker/release.sh; fi'
  - stage: Build
    name: Helm chart
    install:
    - source ./ci/helm/install_helm.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/az/install.sh && ./ci/az/login.sh; fi'
    script:
    - ./ci/helm/tag.sh
    - ./ci/helm/add_pod_annotations.sh
    - ./ci/helm/build.sh
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/helm/release.sh; fi'
  - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
    stage: Versioning
    name: Set tag and update version
    script:
    - "./ci/versioning/add_tag_to_git.sh"
    - "./ci/versioning/set_next_version.sh"
  - if: branch = env(SNAPSHOT_BRANCH) AND type != "pull_request"
    stage: Trigger downstream
    name: Trigger workspace build
    install: skip
    script:
    - sh ./ci/trigger-travis/trigger-travis.sh --pro --branch dev $ORG workspace $TRAVIS_ACCESS_TOKEN
