@startuml Example data model

title Example instantiated data model for Fairspace

enum Access {
    Read
    Write
    Manage
}

class Resource {
    URI iri
    String label
}

class User extends Resource {
    String username
}

class Workspace extends Resource {
    String name
}
Workspace "*" -- "*" User
(Workspace, User) . Access

class File extends Resource {
    String path
}

class Collection extends Resource {
    String name
}
Collection "1" *- "*" File
Collection "*" -- "*" User
(Collection, User) . Access

class Code {
    String system
    String code
    String label
}

abstract class Identifier

class Patient extends Resource {
    String identifier
    Code gender
    Date birthDate
}

class Sample extends Resource {
    String identifier
    Code bodySite
    Code type
    Code status
}
Sample "1" -- "*" Patient : subject

class ResearchStudy extends Resource {
    String identifier
    String title
    String description
    Code status
    Code phase
    Code category
    Code condition
    Code location
    Period period
}

class Consent {
    String identifier
    Code status
    Code scope
    Code category
    DateTime dateTime
}

class ResearchSubject {
    String identifier
    Code status
    Period period
    String assignedArm
    String actualArm
    Consent consent
}
ResearchSubject "1" -- "1" Consent

ResearchStudy -- Patient
(ResearchStudy, Patient) . ResearchSubject

Collection -- Patient
Collection -- Sample
File -- Patient
File -- Sample

Workspace -- ResearchStudy

@enduml
