language: node_js

node_js:
  - "node"

cache:
  directories:
  - node_modules

jobs:
  include:
  - stage: Test
    name: Run E2E tests
    install:
    - npm install cypress
    script:
    - node_modules/.bin/cypress run

notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      - secure: "aT3t6rdZz7H6FUsq2WMtaOgCz00OKe+VLcYM+Q5qZQBcao8T1o607F5op3ZsHj86y6T+yj1qeEopwks0KPb2oGYzpTD+/Wf5+1HnPtTjWAbBaSoMaVF88i5BgPp/7EDrye5dNfyMxPuHCSBxJFTrIikZgbywnm0yl+tcd2B3K1CNugDA6ky4xaDEF9qJzwOoohQSeHnnly6OxaZDywAvI21ENAxEnsIAnsFnKiqWrX8ECMMAtiIVGNpa4R6zIuUtRfcGUgwcDetexGAgsWMAZIHauzDBfLO6+/1E/mSqW3qDVOvBrn9erCBW45skruQ62QbUv4iGpFJwXYsh/ENxr3mytUnntvd23DXbmVUDHMPaEjOnhQVxxhNxew3OiXnfmHv0J7AS4ti7jTtbVVdw29AyDhFSlb5Erfo/z3CP0EmEtHabKoL1Dv6x8hMMuQKcJ9B2CbPX/hGBRmwJio6EqSsXsGq4G/iUP4BzqzOG3y/2RwKvIBJDJqalfbHOadhNCnCLedpIwIC9bUpN5a/4MKrWP7qcd46Ll+4eExcsIj16ez3Gy9Ljuh8CW30Ga5EDmuc/VVNChQVvdq+yLzHmGqK107KzJuZqZM8RL9H9iK4xr7kMZ9mId0U/QjHR7j1zDC9Aa2mL95jUTFbmpFBNuQLMqcd1XIHwThQVKhPRULA="
    template:
      - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true
