{{- $scripts := .Values.workspace.configurationScripts.rabbitmq -}}
{{- if $scripts.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-rabbitmq-configuration"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-rabbitmq-configuration"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: configure-rabbitmq-job
        image: "{{ $scripts.image }}"
        imagePullPolicy: {{ $scripts.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /home/config
        command:
        - "/home/scripts/setup-rabbitmq-workspace.sh"
        - "/home/config/rabbitmq.conf"
        - "/home/config/commands.txt"
      volumes:
      - name: config-volume
        configMap:
          name: "{{.Release.Name}}-rabbitmq-config-map"
{{- end -}}
