# Application's port
port: 8080
publicUrl: http://localhost:8080
elasticsearchUrl: http://localhost:9200
jena:
  # Base IRI for all metadata entities
  metadataBaseIRI: "http://localhost/iri/"
  # Jena's TDB2 database path
  datasetPath: "data/db"
  storeParams:
    tdb.file_mode: "mapped"
    tdb.block_size: 8192
    tdb.block_read_cache_size: 5000
    tdb.block_write_cache_size: 1000
    tdb.node2nodeid_cache_size: 200000
    tdb.nodeid2node_cache_size: 750000
    tdb.node_miss_cache_size: 1000
    tdb.nodetable: "nodes"
    tdb.triple_index_primary: "SPO"
    tdb.triple_indexes:
      - "SPO"
      - "POS"
      - "OSP"
    tdb.quad_index_primary: "GSPO"
    tdb.quad_indexes:
      - "GSPO"
      - "GPOS"
      - "GOSP"
      - "POSG"
      - "OSPG"
      - "SPOG"
    tdb.prefixtable: "prefixes"
    tdb.prefix_index_primary: "GPU"
    tdb.prefix_indexes:
      - "GPU"
  # Path of the transaction log
  transactionLogPath: "data/log"
  bulkTransactions: true
  elasticSearch:
    settings:
      # Map of hosts and ports. The host could also be an IP Address
      hostToPortMapping:
        "127.0.0.1": 9300
      # Name of the Cluster. Defaults to "elasticsearch". Set to "docker-cluster" for a dockerized ES setup.
      clusterName: "docker-cluster"
      # Number of shards. Defaults to 1
      shards: 1
      # Number of replicas. Defaults to 1
      replicas: 1
    advancedSettings:
auth:
  authServerUrl: http://localhost:5100/auth/
  realm: fairspace
  clientId: workspace-client
  enableBasicAuth: true
  superAdminUser: organisation-admin
webDAV:
  # Path of the WebDAV's local blob store
  blobStorePath: "data/blobs"
mail:
  mail.from: info@fairspace.com
  mail.user: user
  mail.password: password
  mail.transport.protocol: smtp
  mail.smtp.auth: true
  mail.smtp.host: host
  mail.smtp.port: 587
  mail.smtp.starttls.enable: true
services:
  jupyterhub: https://jupyter.org/hub#
  cbioportal: https://www.cbioportal.org
  "test username": http://google.com?q=${username}
features:
  - MetadataEditing
search:
  facets:
    - name: collection
      title: Collection
      type: id
      query: |
        PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX curie: <https://institut-curie.org/ontology#>
        PREFIX fs:    <http://fairspace.io/ontology#>
        SELECT DISTINCT ?value ?label
        WHERE {
          ?value a fs:Collection ;
                 rdfs:label ?label .
          FILTER NOT EXISTS { ?value fs:dateDeleted ?anyDateDeleted }
        }
        ORDER BY ?label
    - name: tumorCellularity
      title: Tumor Cellularity
      type: number
      property: https://institut-curie.org/ontology#tumorCellularity
      query:
  views:
    - name: collections
      title: Collections
      columns:
        - name: collection
          title: Collection
          type: id
      query: |
        PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX curie: <https://institut-curie.org/ontology#>
        PREFIX fs:    <http://fairspace.io/ontology#>
        SELECT DISTINCT ?resource ?workspace
        WHERE {
          ?file fs:belngsTo* ?collection .
          ?collection a fs:Collection ;
             fs:ownedBy ?workspace .
        }
    - name: samples
      title: Samples
      columns:
        - name: sample
          title: Sample
          type: id
        - name: tumorCellularity
          title: Tumor Cellularity
          type: number
        - name: description
          title: Description
          type: text
      query: |
        PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX curie: <https://institut-curie.org/ontology#>
        PREFIX fs:    <http://fairspace.io/ontology#>
        SELECT DISTINCT (?sample AS ?resource) ?description ?tumorCellularity ?origin ?topography ?nature ?collectDate
        WHERE {
          ?file curie:sample/curie:isChildOf* ?sample .
          OPTIONAL { ?sample curie:tumorCellularity ?tumorCellularity }
          OPTIONAL { ?sample rdfs:comment ?description }
          OPTIONAL { ?sample curie:hasOrigin ?origin }
          OPTIONAL { ?sample curie:topography ?topography }
          OPTIONAL { ?sample rdfs:isOfNature ?nature }
          OPTIONAL { ?sample curie:collectDate ?collectDate }

          FILTER NOT EXISTS { ?sample fs:dateDeleted ?anyDateDeleted }
        }