baseURI: "http://localhost"
port: 8080
jena:
  datasetPath: "data/db"
  transactionLogPath: "data/log"
  vocabularyURI: "http://fairspace.io/vocabulary#"
  elasticSearch:
    enabled: true
    settings:
      hostToPortMapping:
        localhost: 9300
      clusterName: "elasticsearch"
      shards: 1
      replicas: 1
      indexName: "fs"
auth:
  authEnabled: false
  jwksUrl: "https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/certs"
  jwtAlgorithm: "RS256"
webDAV:
  blobStorePath: "data/blobs"
