# Application's port
port: 8080
publicUrl: http://localhost:8080
elasticsearchUrl: http://localhost:9200
jena:
  # Base IRI for all metadata entities
  metadataBaseIRI: "http://localhost/iri/"
  # Jena's TDB2 database path
  datasetPath: "data/db"
  storeParams:
    tdb.file_mode: "mapped"
    tdb.block_size: 8192
    tdb.block_read_cache_size: 5000
    tdb.block_write_cache_size: 1000
    tdb.node2nodeid_cache_size: 200000
    tdb.nodeid2node_cache_size: 750000
    tdb.node_miss_cache_size: 1000
    tdb.nodetable: "nodes"
    tdb.triple_index_primary: "SPO"
    tdb.triple_indexes:
      - "SPO"
      - "POS"
      - "OSP"
    tdb.quad_index_primary: "GSPO"
    tdb.quad_indexes:
      - "GSPO"
      - "GPOS"
      - "GOSP"
      - "POSG"
      - "OSPG"
      - "SPOG"
    tdb.prefixtable: "prefixes"
    tdb.prefix_index_primary: "GPU"
    tdb.prefix_indexes:
      - "GPU"
  # Path of the transaction log
  transactionLogPath: "data/log"
  bulkTransactions: true
  elasticSearch:
    settings:
      # Map of hosts and ports. The host could also be an IP Address
      hostToPortMapping:
        "127.0.0.1": 9300
      # Name of the Cluster. Defaults to "elasticsearch". Set to "docker-cluster" for a dockerized ES setup.
      clusterName: "docker-cluster"
      # Number of shards. Defaults to 1
      shards: 1
      # Number of replicas. Defaults to 1
      replicas: 1
    advancedSettings:
auth:
  authServerUrl: http://localhost:5100/auth/
  realm: fairspace
  clientId: workspace-client
  enableBasicAuth: true
  superAdminUser: organisation-admin
webDAV:
  # Path of the WebDAV's local blob store
  blobStorePath: "data/blobs"
mail:
  mail.from: info@fairspace.com
  mail.user: user
  mail.password: password
  mail.transport.protocol: smtp
  mail.smtp.auth: true
  mail.smtp.host: host
  mail.smtp.port: 587
  mail.smtp.starttls.enable: true
services:
  jupyterhub: https://jupyter.org/hub#
  cbioportal: https://www.cbioportal.org
  "test username": http://google.com?q=${username}
features:
  - MetadataEditing
search:
  pageRequestTimeout: 3000
  countRequestTimeout: 30000
  facets:
    - name: topography
      title: Topography
      type: id
      query: |
        PREFIX curie: <https://institut-curie.org/ontology#>
        SELECT ?topography
        WHERE {
           ?topography a curie:Topography .
           FILTER EXISTS { ?x curie:topography ?topography }
        }
    - name: sampleNature
      title: Sample Nature
      type: id
      query: |
        PREFIX curie: <https://institut-curie.org/ontology#>
        SELECT ?nature
        WHERE {
           ?nature a curie:SampleNature .
           FILTER EXISTS { ?x curie:isOfNature ?nature }
        }
    - name: sampleOrigin
      title: Sample Origin
      type: id
      query:
    - name: tumorCellularity
      title: Tumor Cellularity
      type: number
      min: 0
      max: 100
    - name: Event Type
      title: eventType
      type: id
      query:
    - name: Morphology
      title: Morphology
      type: id
      query:
    - name: Laterality
      title: Laterality
      type: id
      query: |
        PREFIX curie: <https://institut-curie.org/ontology#>
        SELECT ?laterality
        WHERE {
           ?laterality a curie:TumorLaterality .
           FILTER EXISTS { ?x curie:laterality ?laterality }
        }
    - name: tumorGradeType
      title: Tumor Grade Type
      type: id
      query:
    - name: tumorGradeValue
      title: Tumor Grade Value
      type: id
      query:
    - name: tnmType
      title: TNM Type
      type: id
      query:
    - name: tnmT
      title: The primary tumor size
      type: id
      query:
    - name: tnmN
      title: The regional lymph nodes
      type: id
      query:
    - name: tnmM
      title: Distant metastasis
      type: id
      query:
    - name: ageAtDiagnosis
      title: Age at Diagnosis
      type: number
      query:
    - name: species
      title: Species
      type: id
      query:
    - name: gender
      title: Gender
      type: id
      query:
    - name: ageAtLastNews
      title: Age at Last News
      type: number
      query:
    - name: ageAtDeath
      title: Age at Death
      type: number
      query:
    - name: collection
      title: Collection
      type: id
      query: |
        PREFIX fs:    <http://fairspace.io/ontology#>

        SELECT ?collection
        WHERE {
          ?collection a fs:Collection ;
          FILTER NOT EXISTS { ?collection fs:dateDeleted ?anyDateDeleted }
        }
  views:
    - name: samples
      title: Samples
      columns:
        - name: sample
          title: Sample
          type: id
        - name: topography
          title: Topography
          type: id
        - name: sampleNature
          title: Sample Nature
          type: id
        - name: sampleOrigin
          title: Sample Origin
          type: id
        - name: tumorCellularity
          title: Tumor Cellularity
          type: number
        - name: event
          title: Tumor Pathology Event
          type: id
        - name: Event Type
          title: eventType
          type: id
        - name: Morphology
          title: Morphology
          type: id
        - name: Laterality
          title: Laterality
          type: id
        - name: tumorGradeType
          title: Tumor Grade Type
          type: id
        - name: tumorGradeValue
          title: Tumor Grade Value
          type: id
        - name: tnmType
          title: TNM Type
          type: id
        - name: tnmT
          title: The primary tumor size
          type: id
        - name: tnmN
          title: The regional lymph nodes
          type: id
        - name: tnmM
          title: Distant metastasis
          type: id
        - name: ageAtDiagnosis
          title: Age at Diagnosis
          type: number
        - name: subject
          title: Subject
          type: id
        - name: species
          title: Species
          type: id
        - name: gender
          title: Gender
          type: id
        - name: ageAtLastNews
          title: Age at Last News
          type: number
        - name: ageAtDeath
          title: Age at Death
          type: number
      query: |
        PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX curie: <https://institut-curie.org/ontology#>
        PREFIX fs:    <http://fairspace.io/ontology#>

        SELECT DISTINCT
          ?sample ?topography ?sampleNature ?sampleOrigin ?tumorCellularity
          ?event ?morphology ?eventType ?laterality ?tumorGradeType ?tumorGradeValue ?tnmType ?tnmT ?tnmN ?tnmM ?ageAtDiagnosis
          ?subject ?gender ?species ?ageAtLastNews ?ageAtDeath
        WHERE {
          ?sample a curie:BiologicalSample .

          OPTIONAL { ?sample curie:diagnosis?/curie:topography ?topography }
          OPTIONAL { ?sample curie:isOfNature ?sampleNature }
          OPTIONAL { ?sample curie:hasOrigin ?sampleOrigin }
          OPTIONAL { ?sample curie:tumorCellularity ?tumorCellularity }

          OPTIONAL { ?sample curie:diagnosis ?event }
          OPTIONAL { ?event curie:tumorMorphology ?morphology }
          OPTIONAL { ?event curie:eventType ?eventType }
          OPTIONAL { ?event curie:tumorLaterality ?laterality }
          OPTIONAL { ?event curie:ageAtDiagnosis ?ageAtDiagnosis }
          OPTIONAL { ?event curie:tumorGradeType ?tumorGradeType }
          OPTIONAL { ?event curie:tumorGradeValue ?tumorGradeValue }
          OPTIONAL { ?event curie:tnmType ?tnmType }
          OPTIONAL { ?event curie:tnmT ?tnmT }
          OPTIONAL { ?event curie:tnmN ?tnmN }
          OPTIONAL { ?event curie:tnmM ?tnmM }

          OPTIONAL { ?sample curie:diagnosis?/curie:subject ?subject }
          OPTIONAL { ?subject curie:gender ?gender }
          OPTIONAL { ?subject curie:isOfSpecies ?species }
          OPTIONAL { ?subject curie:ageAtLastNews ?ageAtLastNews }
          OPTIONAL { ?subject curie:ageAtDeath ?ageAtDeath }

          OPTIONAL { ?collection a fs:Collection ; fs:contains*/curie:aboutMaterial ?sample }

          FILTER NOT EXISTS { ?sample fs:dateDeleted ?anyDateDeleted }
        }
    - name: events
      title: Tumor Pathology Events
      columns:
        - name: event
          title: Tumor Pathology Event
          type: id
        - name: Event Type
          title: eventType
          type: id
        - name: topography
          title: Topography
          type: id
        - name: Morphology
          title: Morphology
          type: id
        - name: Laterality
          title: Laterality
          type: id
        - name: ageAtDiagnosis
          title: Age at Diagnosis
          type: number
        - name: tumorGradeType
          title: Tumor Grade Type
          type: id
        - name: tumorGradeValue
          title: Tumor Grade Value
          type: id
        - name: tnmType
          title: TNM Type
          type: id
        - name: tnmT
          title: The primary tumor size
          type: id
        - name: tnmN
          title: The regional lymph nodes
          type: id
        - name: tnmM
          title: Distant metastasis
          type: id
        - name: subject
          title: Subject
          type: id
        - name: species
          title: Species
          type: id
        - name: gender
          title: Gender
          type: id
        - name: ageAtLastNews
          title: Age at Last News
          type: number
        - name: ageAtDeath
          title: Age at Death
          type: number
      query: |
        PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX curie: <https://institut-curie.org/ontology#>
        PREFIX fs:    <http://fairspace.io/ontology#>

        SELECT DISTINCT
          ?event ?eventType ?morphology ?topography ?laterality ?tumorGradeType ?tumorGradeValue ?tnmType ?tnmT ?tnmN ?tnmM ?ageAtDiagnosis
          ?subject ?gender ?species ?ageAtLastNews ?ageAtDeath
        WHERE {
          ?sample a curie:BiologicalSample .

          OPTIONAL { ?sample curie:diagnosis?/curie:topography ?topography }
          OPTIONAL { ?sample curie:isOfNature ?sampleNature }
          OPTIONAL { ?sample curie:hasOrigin ?sampleOrigin }
          OPTIONAL { ?sample curie:tumorCellularity ?tumorCellularity }

          OPTIONAL { ?sample curie:diagnosis ?event }
          OPTIONAL { ?event curie:tumorMorphology ?morphology }
          OPTIONAL { ?event curie:eventType ?eventType }
          OPTIONAL { ?event curie:tumorLaterality ?laterality }
          OPTIONAL { ?event curie:ageAtDiagnosis ?ageAtDiagnosis }
          OPTIONAL { ?event curie:tumorGradeType ?tumorGradeType }
          OPTIONAL { ?event curie:tumorGradeValue ?tumorGradeValue }
          OPTIONAL { ?event curie:tnmType ?tnmType }
          OPTIONAL { ?event curie:tnmT ?tnmT }
          OPTIONAL { ?event curie:tnmN ?tnmN }
          OPTIONAL { ?event curie:tnmM ?tnmM }

          OPTIONAL { ?sample curie:diagnosis?/curie:subject ?subject }
          OPTIONAL { ?subject curie:gender ?gender }
          OPTIONAL { ?subject curie:isOfSpecies ?species }
          OPTIONAL { ?subject curie:ageAtLastNews ?ageAtLastNews }
          OPTIONAL { ?subject curie:ageAtDeath ?ageAtDeath }

          OPTIONAL { ?collection a fs:Collection ; fs:contains*/curie:aboutMaterial ?sample }

          FILTER NOT EXISTS { ?sample fs:dateDeleted ?anyDateDeleted }
        }
    - name: subjects
      title: Subjects
      columns:
        - name: subject
          title: Subject
          type: id
        - name: species
          title: Species
          type: id
        - name: gender
          title: Gender
          type: id
        - name: ageAtLastNews
          title: Age at Last News
          type: number
        - name: ageAtDeath
          title: Age at Death
          type: number
      query: |
        PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX curie: <https://institut-curie.org/ontology#>
        PREFIX fs:    <http://fairspace.io/ontology#>

        SELECT DISTINCT
          ?subject ?species ?gender ?ageAtLastNews ?ageAtDeath
        WHERE {
          ?subject a curie:Subject .

          OPTIONAL { ?sample curie:subject ?subject .
            OPTIONAL { ?sample curie:topography ?topography }
            OPTIONAL { ?sample curie:isOfNature ?sampleNature }
            OPTIONAL { ?sample curie:hasOrigin ?sampleOrigin }
            OPTIONAL { ?sample curie:tumorCellularity ?tumorCellularity }
          }

          OPTIONAL { ?event curie:subject ?subject ;
            OPTIONAL { ?event curie:tumorMorphology ?morphology }
            OPTIONAL { ?event curie:eventType ?eventType }
            OPTIONAL { ?event curie:tumorLaterality ?laterality }
            OPTIONAL { ?event curie:ageAtDiagnosis ?ageAtDiagnosis }
            OPTIONAL { ?event curie:tumorGradeType ?tumorGradeType }
            OPTIONAL { ?event curie:tumorGradeValue ?tumorGradeValue }
            OPTIONAL { ?event curie:tnmType ?tnmType }
            OPTIONAL { ?event curie:tnmT ?tnmT }
            OPTIONAL { ?event curie:tnmN ?tnmN }
            OPTIONAL { ?event curie:tnmM ?tnmM }
          }

          OPTIONAL { ?subject curie:gender ?gender }
          OPTIONAL { ?subject curie:isOfSpecies ?species }
          OPTIONAL { ?subject curie:ageAtLastNews ?ageAtLastNews }
          OPTIONAL { ?subject curie:ageAtDeath ?ageAtDeath }

          OPTIONAL { ?collection a fs:Collection ; fs:contains*/curie:aboutMaterial ?sample }

          FILTER NOT EXISTS { ?subject fs:dateDeleted ?anyDateDeleted }
        }