dependencies:
- name: jupyterhub
  version: "0.6"
  repository: https://jupyterhub.github.io/helm-chart/
- name: pluto
  version: v0.0.7
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: mercury
  version: v0.0.2
  repository: https://chartmuseum.jx.test.fairdev.app/
