dependencies:
#- name: jupyterhub
#  version: "0.6"
#  repository: https://jupyterhub.github.io/helm-chart/
- name: pluto
  version: v0.1.22
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: mercury
  version: v0.1.7
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: hydra
  version: v0.1.5
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: minio
  version: v1.3.4
  repository: "@stable"
