dependencies:
#- name: jupyterhub
#  version: "0.6"
#  repository: https://jupyterhub.github.io/helm-chart/
- name: pluto
  version: v0.1.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: mercury
  version: v0.1.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: hydra
  version: v0.1.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: ceres
  version: v0.1.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: neptune
  version: v0.2.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: minio
  version: v1.3.4
  repository: "@stable"

