# Default values for vre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Set specific workspace name. Defaults to release name
# Please note that if this is set, also set it for pluto in `pluto.workspace.name`
nameOverride:

replicaCount: 1

image:
  repository: docker-registry.jx.test.fairdev.app/fairspace/workspace
  tag: 0.1.68
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Hyperspace that this workspace is connected to
# Please note that pluto also has to know about the
# keycloak baseUrl and realm, see the pluto configuration
hyperspace:
    tls: true
    domain:
    locationOverrides:
        keycloak:

    # TODO: determine better way to handle keycloak credentials
    # Keycloak credentials are needed to setup the workspace (e.g. users, clients)
    # in keycloak. Please note that this is not a sustainable way of doing, due
    # to the sensitive nature of these parameters
    #
    # We could either:
    # - have the hyperspace setup keycloak itself, when creating a new workspace
    # - use temporary credentials for setting up these users
    # - ...
    keycloak:
        username:
        password:
        realm:
        clientSecret:


# Setup ingress for workspace components
workspace:
    ingress:
        enabled: true
        domain:
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns

    testuser:
         password: fairspace123

    # Scripts for setting up keycloak for a workspace
    configurationScripts:
        dockerRepository: docker-registry.jx.test.fairdev.app
        image: fairspace/keycloak-configuration
        configurationScriptsTag: 0.0.10
        pullPolicy: IfNotPresent

# Specific settings for pluto
# Default configuration points to hydra, mercury and neptune
# in the same workspace
pluto:
  overrides:
    keycloak:
      client:
        secretNamePostfix: oauth-client

  keycloak:
    baseUrl:
    realm:
    redirectAfterLogoutUrl: https://fairspace.com

# Specific setting for hydra
# Default configuration points to minio in the same workspace
# and uses the credentials from the minio secret
hydra:
  app:
    oauth2:
      baseUrl:
      realm:

  overrides:
    minio:
      secretNamePostfix: minio

# Specific settings for JupyterHub subchart
jupyterhub:
    singleuser:
      image:
        name: "docker-registry.jx.test.fairdev.app/fairspace/jupyterhub-singleuser"
        tag: 0.1.68
      defaultUrl: "/lab"
    hub:
        ingress:
            enabled: false
        extraEnv:
            JUPYTER_ENABLE_LAB: 1
        extraConfig: |
            c.KubeSpawner.cmd = ['jupyter-labhub']
    proxy:
        secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"

# Specific settings for Minio subchart
minio:
  accessKey: IFGZ2M0W8LB0C92FYA3J
  secretKey: xzow1FrinP+oJYEpHP3s6NzayewFFOgAf/nudLSB
  mode: standalone
  persistence:
    enabled: true

# Specific setting for mercury on what url to access the storage
mercury:
  urls:
    storage:

# Specific settings for Ceres subchart
ceres:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      subPath: "ceres-db"
      mountPath: /data/ceres
    ceres:
      auth:
        enabled: true
        jwt:
          issuer: 
          realm: 
          audience: 

# Specific settings for Neptune subchart
neptune:
    ceres:
      model: default

    app:
      oauth2:
        baseUrl: 
        realm: 
