kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pluto.fullname" . }}-oauth
type: Opaque
data:
  clientId: {{ .Values.keycloak.client.id | default (printf "%s-pluto" .Values.workspace.name) | b64enc | quote }}
  clientSecret: {{ .Values.keycloak.client.secret | default "" | b64enc | quote }}
