{{- if not .Values.overrideTemplates.keycloak.client.secretName -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pluto.fullname" . }}-oauth
type: Opaque
data:
  clientId: {{ .Values.keycloak.client.id | default (printf "%s-pluto" (include "pluto.workspace.name" .)) | b64enc | quote }}
  clientSecret: {{ .Values.keycloak.client.secret | default "" | b64enc | quote }}
{{- end -}}