{{- $scripts := .Values.fairspace.configurationScripts.keycloak -}}
{{- if $scripts.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-keycloak-teardown"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-keycloak-teardown"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: configure-keycloak-job
        image: "{{ $scripts.dockerRepository }}/{{ $scripts.image }}:{{ $scripts.configurationScriptsTag }}"
        imagePullPolicy: {{ $scripts.pullPolicy }}
        resources:
{{ toYaml $scripts.resources | indent 10 }}
        env:
          - name: LOGIN_REALM
            value: {{ .Values.external.keycloak.loginRealm }}
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ template "fairspace.fullname" . }}-keycloak-creds-teardown"
                key: password
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-oauth-client"
                key: clientSecret
        command:
        - "/opt/jboss/scripts/teardown-keycloak-fairspace.sh"
        - "{{ template "keycloak.baseUrl" . }}/auth"
        - "{{.Values.external.keycloak.username}}"
        - "{{.Values.external.keycloak.realm}}"
        - "{{ template "fairspace.name" . }}"
{{- end -}}
